from enum import Enum
import logging
import concurrent.futures
import pandas as pd
import numpy as np
from functools import partial
from typing import Dict, List, Tuple, Optional, Any, Union
from pathlib import Path
from sklearn.cluster import DBSCAN
from moleculekit.molecule import Molecule

from .utils import load_json, parse_msa_metrics
from .model import Engine, Model
from .metrics import (
    calculate_all_metrics,
    calculate_ipsae,
    calculate_LIS_family,
    calculate_pdockq,
    calculate_pdockq2,
)
from .plotting import plot_boxplots, plot_iptm_vs_ptm, plot_pae_clusters, plot_paes, plot_plddt

logger = logging.getLogger(__name__)


class InteractomeMode(Enum):
    MONOMER = "single"
    INTRA_PAIRS = "intra_pairs"
    INTER_PAIRS = "inter_pairs"
    HOMOMERS = "homomers"


class InteractomeProcessor:
    """
    Analyzes the output models generated by folding engines (AF3 or Boltz).

    This class is responsible for parsing model files (CIF/JSON), extracting 
    quality metrics (pLDDT, PAE, ipTM...), and organizing the data into 
    DataFrames for heteromers and homomers.

    Attributes:
        model_paths (List[Path]): List of paths to the model directories or files to analyze.
        engine (str): The engine used to generate the models ('af3' or 'boltz').
        df_het (Optional[pd.DataFrame]): DataFrame containing metrics for heteromeric complexes.
        df_hom (Optional[pd.DataFrame]): DataFrame containing metrics for homomeric complexes.
        cluster_data (Optional[pd.DataFrame]): DataFrame containing clustering results (if applicable).
    """
    # _SUPPORTED_ENGINES = {"af3", "boltz", "colabfold"}

    def __init__(self, model_list: List[Union[str, Path]], engine: Engine | str = Engine.COLABFOLD, mode: InteractomeMode | str = InteractomeMode.INTRA_PAIRS):
        """
        Initializes the InteractomeProcessor.

        Args:
            model_list (List[Union[str, Path]]): A list of paths pointing to the 
                results to be processed. Can be strings or Path objects.
            engine (str, optional): The folding engine used. Case-insensitive. 
                Must be 'af3' or 'boltz'. Defaults to "af3".
            mode (str, optional): The mode of interaction analysis. Case-insensitive.
                Must be one of 'monomer', 'intra_pairs', 'inter_pairs', or 'homomers'.
                Defaults to 'inter_pairs'.

        Raises:
            ValueError: If the provided engine is not supported.
        """
        try:
            self._engine = Engine(engine.lower()) if isinstance(engine, str) else engine
        except ValueError:
            valid = ", ".join(e.value for e in Engine)
            raise ValueError(f"Engine should be one of: {valid}")
        self._mode = InteractomeMode(mode.lower()) if isinstance(mode, str) else mode

        # Sanitize Paths (Convert all to Path objects)
        self.model_paths = [Path(p) for p in model_list]
        
        if not self.model_paths:
            logger.warning("InteractomeProcessor initialized with an empty model list.")
        else:
            logger.info(f"Initialized Processor for {len(self.model_paths)} models using engine '{self._engine}'")

        # Initialize Data Containers. We explicitly type hint these as DataFrames or None
        self.df_het: Optional[pd.DataFrame] = None
        self.df_hom: Optional[pd.DataFrame] = None
        self.cluster_data: Optional[pd.DataFrame] = None

    @property
    def engine(self) -> str:
        return self._engine.value

    @staticmethod
    def cluster_pae(pae_submatrix: np.ndarray, threshold:float = 15.0, eps:float = 10.0, min_samples: int = 5)-> Tuple[np.ndarray, np.ndarray]:
        """
        Clusters low PAE regions in a PAE submatrix using DBSCAN algorithm.

        This utility method identifies coordinates where the Predicted Aligned Error (PAE)
        is below a specified threshold and groups them spatially using density-based clustering.

        Args:
            pae_submatrix (np.ndarray): A 2D array representing the PAE matrix subset.
            threshold (float, optional): The maximum PAE value to be considered a 'contact'. 
                Defaults to 15.0.
            eps (float, optional): The maximum distance between two samples for one to be 
                considered as in the neighborhood of the other (DBSCAN param). Defaults to 10.0.
            min_samples (int, optional): The number of samples in a neighborhood for a point 
                to be considered as a core point. Defaults to 5.

       Returns:
            Tuple[np.ndarray, np.ndarray]: 
                - coords (np.ndarray): Array of shape (N, 2) with [row, col] coordinates.
                - labels (np.ndarray): Array of shape (N,) with cluster labels (-1 for noise).
                Returns empty arrays if no points satisfy the threshold.

        """
        # Find coordinates below threshold
        # np.argwhere returns indices of shape (N, 2) directly.
        low_pae_coords = np.argwhere(pae_submatrix < threshold)
        
        # Early Exit (Fail Fast)
        if low_pae_coords.size == 0:
            # Return empty numpy arrays to maintain type consistency
            # Shape (0, 2) for coords, Shape (0,) for labels
            return np.empty((0, 2), dtype=int), np.array([], dtype=int)
        

        #Apply DBSCAN clustering
        clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(low_pae_coords)
        labels = clustering.labels_
        return  low_pae_coords, labels

    @staticmethod
    def cluster_info(low_coords: np.ndarray, cluster_labels: np.ndarray)-> pd.DataFrame:
        
        """
        Extracts geometric stats from clustered PAE coordinates (bounding box, center, density).

        Analyzes output from DBSCAN. For each cluster, calculates the bounding box 
        dimensions and centroids to characterize the interaction interface shape.
        
        Note on Coordinates: 
        Assumes Matrix notation (Row, Col). Maps Row -> Y, Col -> X.

        Args:
            low_coords (np.ndarray): Shape (N, 2). Coordinates [row, col].
            cluster_labels (np.ndarray): Shape (N,). Cluster ID for each point.

        Returns:
            pd.DataFrame: Contains columns ['cluster_id', 'num_points', 'x_min', 
            'x_max', 'y_min', 'y_max', 'x_len', 'y_len', 'center_x', 'center_y', 
            'aspect_ratio'].
        """

        unique_labels = np.unique(cluster_labels)
        cluster_info_list = []

        for label in unique_labels:
            # -1 represents noise in DBSCAN
            if label == -1:
                continue 

            # Boolean masking to select points belonging to this cluster
            cluster_points = low_coords[cluster_labels == label]
            
            # --- Coordinate Logic ---
            # Numpy: Axis 0 = Rows (Y), Axis 1 = Cols (X)
            rows = cluster_points[:, 0]
            cols = cluster_points[:, 1]

            # Calculate Bounding Box
            y_min, y_max = np.min(rows), np.max(rows)
            x_min, x_max = np.min(cols), np.max(cols)


            # Dimensions
            y_len = y_max - y_min
            x_len = x_max - x_min

            # Center of Mass 
            center_row = np.mean(rows)
            center_col = np.mean(cols)
            
            # Cluster Ratio (Longest side / Shortest side)
            min_side = min(x_len, y_len)
            max_side = max(x_len, y_len)
            cluster_ratio = max_side / min_side if min_side > 0 else 0.0
            
            cluster_info_list.append({
                "cluster_id": label,
                "num_points": len(cluster_points),
                "x_len": x_len,
                "y_len": y_len,
                "x_min": x_min,
                "x_max": x_max,
                "y_min": y_min,
                "y_max": y_max,
                "center_x": round(center_col, 2), # Col is X
                "center_y": round(center_row, 2), # Col is Y
                "cluster_ratio": round(cluster_ratio, 2)
            })

        # Define columns explicitly to ensure DataFrame structure even if empty
        columns = [
            "cluster_id", "num_points", 
            "x_len", "y_len", "x_min", "x_max", 
            "y_min", "y_max", "center_x", "center_y", "cluster_ratio"
        ]

        return pd.DataFrame(cluster_info_list, columns=columns)
    
    def process_ppi(self, model_file: Union[str, Path],
                    prefix: str = "") -> Tuple[Dict[str, Any], pd.DataFrame]:
        """
        Processes a single CIF model file using the engine set at construction.

        Args:
            model_file: Path to the model .cif file.
            prefix: Substring to strip from the parent directory name when parsing PPI IDs.

        Returns:
            Tuple of (summary_dict, cluster_data_df).
        """
        path_obj = Path(model_file)

        dir_name = path_obj.parent.name
        ppi_id = dir_name.replace(prefix, "")
        parts = ppi_id.split("__")
        orf_a = parts[0]
        orf_b = parts[1] if len(parts) > 1 else ""
        model_number = int(path_obj.stem.split("model_")[-1].split("_")[0])

        model = Model(path_obj, self._engine)
        m = model.metrics
        md = model.model_data
        chain_ids = md.token_chain_ids

        plddt_path = path_obj.with_name(f"{path_obj.stem}_plddt.png")
        plot_plddt(m.ca_plddts, md.chain_boundaries_by_res, chain_ids, str(plddt_path))

        pae_path = path_obj.with_name(f"{path_obj.stem}_pae.png")
        plot_paes(m.pae, md.chain_boundaries_by_res, set(chain_ids),
                  f"{m.iptm} ipTM - {m.ptm} pTM", str(pae_path))

        if self._mode in [InteractomeMode.HOMOMERS, InteractomeMode.MONOMER]:
            return {
                "PPI": ppi_id,
                "ORF": orf_a,
                "Num_copies": orf_b,
                "Model_num": model_number,
                "mean_plddt": float(m.ca_plddts.mean()),
                "mean_pae": float(m.pae.mean()),
                "ipTM": m.iptm,
                "pTM": m.ptm,
                "Path": str(path_obj),
            }, pd.DataFrame()

        # INTER_PAIRS / INTRA_PAIRS — interface analysis
        unique_chains = sorted(set(chain_ids))
        chain_a, chain_b = unique_chains[0], unique_chains[1]

        metrics_input = {
            "pae": m.pae,
            "cb_plddts": m.cb_plddts,
            "token_chain_ids": chain_ids,
        }
        all_metrics = calculate_all_metrics(str(path_obj), metrics_input)

        pae_submatrix_1 = m.pae[chain_ids == chain_a][:, chain_ids == chain_b]
        pae_submatrix_2 = m.pae[chain_ids == chain_b][:, chain_ids == chain_a].T
        submatrix = np.mean([pae_submatrix_1, pae_submatrix_2], axis=0)

        low_coords, cluster_labels = InteractomeProcessor.cluster_pae(submatrix)

        cluster_plot_path = path_obj.with_name(f"{path_obj.stem}_cluster.png")
        plot_pae_clusters(submatrix, low_coords, cluster_labels, save_name=str(cluster_plot_path))

        cluster_data = InteractomeProcessor.cluster_info(low_coords=low_coords, cluster_labels=cluster_labels)
        if not cluster_data.empty:
            cluster_data["PPI"] = ppi_id
            cluster_data["model_num"] = model_number
            cluster_data["path"] = str(path_obj)

        summary_dict = {
            "PPI": ppi_id,
            "ORF_A": orf_a,
            "ORF_B": orf_b,
            "Folder": str(path_obj.parent),
            "Path": str(path_obj),
            "Model_num": model_number,
            "ipTM": m.iptm,
            "pTM": m.ptm,
            "pTM_chain_A": float(m.iptm_chain_pair[0][0]),
            "pTM_chain_B": float(m.iptm_chain_pair[1][1]),
            **all_metrics,
        }

        return summary_dict, cluster_data
    
    def process_models(self,
                       output_path: Union[str, Path] = ".",
                       prefix: str = "", 
                       **kwargs)-> None:
        """
        Orchestrates the parallel processing of protein models and saves results to CSV.

        This method manages the full pipeline execution. It implements a 'resume' logic by
        checking for existing output files and skipping models that have already been processed.
        It utilizes a process pool to distribute the workload across multiple CPU cores and
        finally aggregates all metrics and cluster data into consolidated CSV files.

        Parameters
        ----------
        output_path : str or Path, optional
            The directory where output CSV files ('interactome_data.csv' and 'clusters_data.csv')
            will be saved. Defaults to current directory (".").
        prefix : str, optional
            A substring to be stripped from directory names when parsing PPI IDs (e.g., to clean
            up common prefixes in folder structures). Defaults to "".
        **kwargs
            Additional keyword arguments passed directly to `concurrent.futures.ProcessPoolExecutor`.
            Most commonly used to set `max_workers` (e.g., `max_workers=4`) to limit CPU usage.

        Returns
        -------
        None
            This method does not return values; it produces side effects (CSV files on disk).
        """
        import tqdm
        # Setup Paths
        out_dir = Path(output_path)
        out_dir.mkdir(parents=True, exist_ok=True)
        interactome_csv = out_dir / "interactome_data.csv"
        clusters_csv = out_dir / "clusters_data.csv"

        # Initialize containers
        interactome_df = pd.DataFrame()
        clusters_df = pd.DataFrame()
        # Models to process (initially all)
        models_to_process = self.model_paths.copy()

        # Resume Logic (Check existing data)
        if interactome_csv.exists():
            logger.info(f"Found existing data at {interactome_csv}. Resuming run...")
            interactome_df = pd.read_csv(interactome_csv)
            if clusters_csv.exists():
                clusters_df = pd.read_csv(clusters_csv)
            # Filter out models that are already in the CSV
            # We assume the 'Path' column contains the path to the model
            if "Path" in interactome_df.columns:
                processed_paths = set(interactome_df["Path"].astype(str))
                    
                # Identify which paths from input are not in the processed set
                # We convert path.parent to string to match the CSV format
                models_to_process = [
                    p for p in models_to_process 
                    if str(p) not in processed_paths
                ]
                logger.info(f"Skipping {len(self.model_paths) - len(models_to_process)} already processed models.")
        if not models_to_process:
            logger.info("All models are already processed. Exiting.")
            return
        
        logger.info(f"Starting parallel processing for {len(models_to_process)} models...")
    
        # Parallel Execution
        new_interactome_list = []
        new_clusters_list = []

        with concurrent.futures.ProcessPoolExecutor(**kwargs) as executor:
            worker = partial(self.process_ppi,
                            #  model_type=self._engine,
                             prefix=prefix)
            
            # tqdm for progress bar
            # map maintains order, which matches models_to_process order
            results_iterator = tqdm.tqdm(
                executor.map(worker, models_to_process), 
                total=len(models_to_process),
                desc="Processing Models"
            )
            for metrics_dict, cluster_df in results_iterator:
                new_interactome_list.append(metrics_dict)
                if not cluster_df.empty:
                    new_clusters_list.append(cluster_df)
        
        # Aggregation
        logger.info("Aggregating and saving results...")  

        # Combine Lists into DataFrames
        new_interactome_df = pd.DataFrame(new_interactome_list)
        # if self._mode in [InteractomeMode.HOMOMERS]:
        #     new_interactome_df.rename(columns={"ORF_A": "ORF", "ORF_B": "N_copies"}, inplace=True)
        
        # if self._mode in [InteractomeMode.INTER_PAIRS, InteractomeMode.INTRA_PAIRS]:
        if new_clusters_list:
            new_clusters_df = pd.concat(new_clusters_list, ignore_index=True)
        else:
            new_clusters_df = pd.DataFrame()  

        # Concatenate with Existing Data (Resume)
        final_interactome_df = pd.concat([interactome_df, new_interactome_df], ignore_index=True)
        final_clusters_df = pd.concat([clusters_df, new_clusters_df], ignore_index=True)
            
        # Save dfs to .csv
        final_interactome_df = final_interactome_df.round(2)
        final_interactome_df.to_csv(interactome_csv, index=False)

        # Formatting Clusters DataFrame
        ## NOTE: I do not know what is going on below... Maybe should be removed
        if self._mode in [InteractomeMode.INTER_PAIRS, InteractomeMode.INTRA_PAIRS] and not final_clusters_df.empty:
            desired_columns = [
                'PPI', 'model_num', 'path', 'cluster_id', 'num_points', 
                'x_len', 'y_len', 'x_min', 'x_max', 'y_min', 'y_max',
                'center_x', 'center_y', 'cluster_ratio'
            ]
        # Ensure columns exist (handle case-sensitivity if old CSV had 'Cluster_ratio')
            # if 'Cluster_ratio' in final_clusters_df.columns and 'cluster_ratio' not in final_clusters_df.columns:
            #     final_clusters_df.rename(columns={'Cluster_ratio': 'cluster_ratio'}, inplace=True)
            
            # Select and order columns safely
            # Only select columns that actually exist to avoid KeyError
            existing_cols = [c for c in desired_columns if c in final_clusters_df.columns]
            final_clusters_df = final_clusters_df[existing_cols]

            final_clusters_df = final_clusters_df.round(2)
            final_clusters_df.to_csv(clusters_csv, index=False)
        
        logger.info(f"Done. Data saved to {out_dir}")

    # ── Pooled ColabFold processing ───────────────────────────────────────────

    _IPTM_SIZE_CORRECTION_INTERCEPT: float = -0.036255571
    _IPTM_SIZE_CORRECTION_SLOPE: float = 0.004470512

    @staticmethod
    def _size_correct_iptm(iptm: float, len_a: int, len_b: int) -> float:
        """Apply size correction to a pairwise ipTM score (Todor et al. 2026).

        Corrects for the systematic positive bias of ipTM with larger protein
        pairs.  Coefficients derived for ~200–500 aa bacterial proteins; the
        direction of the correction is valid for viral proteins as well.

        Returns ``iptm - expected_iptm`` where
        ``expected_iptm = intercept + slope * sqrt(len_a + len_b)``.
        """
        expected = (
            InteractomeProcessor._IPTM_SIZE_CORRECTION_INTERCEPT
            + InteractomeProcessor._IPTM_SIZE_CORRECTION_SLOPE * np.sqrt(len_a + len_b)
        )
        return float(iptm - expected)

    @staticmethod
    def _process_pool_model(
        cif_path: Path,
        chain_to_protein: Dict[str, str],
        engine: Engine,
        ppi_separator: str = "__",
    ) -> List[Dict[str, Any]]:
        """Extract pairwise metrics for every protein pair in one pool model.

        Computes structural metrics (ipSAE, LIS family, pDockQ2, pLDDT, PAE)
        for all unique unordered chain pairs in a pooled multimer CIF.
        Metric DataFrames are computed once per file and sliced per pair.

        Parameters
        ----------
        cif_path : Path
            Path to the ColabFold multimer CIF file.
        chain_to_protein : Dict[str, str]
            Mapping of chain letter → protein ID in pool order
            (e.g. ``{'A': 'E1A', 'B': 'pVII', 'C': 'fiber'}``).
        engine : Engine
            Folding engine (must be :attr:`Engine.COLABFOLD`).
        ppi_separator : str
            Separator used to build PPI identifiers. Defaults to ``'__'``.

        Returns
        -------
        List[dict]
            One dict per unique protein pair with all metric columns plus
            ``PPI``, ``ORF_A``, ``ORF_B``, ``Path``, ``ipTM``,
            ``size_corrected_ipTM``.
        """
        model = Model(cif_path, engine)
        m = model.metrics
        md = model.model_data
        chain_ids = np.array(md.token_chain_ids)
        model_chains = np.unique(chain_ids)
        chain_to_idx: Dict[str, int] = {c: i for i, c in enumerate(model_chains)}

        cif_str = str(cif_path)
        ipsae_df  = calculate_ipsae(cif_str, m.pae)
        lis_df    = calculate_LIS_family(cif_str, m.pae)
        pdockq2_df = calculate_pdockq2(cif_str, plddt_by_res=m.cb_plddts, pae_matrix=m.pae)

        def _ipsae_val(c1: str, c2: str, col: str) -> float:
            row = ipsae_df.loc[(ipsae_df.chain1 == c1) & (ipsae_df.chain2 == c2), col]
            return float(row.values[0]) if len(row) > 0 else 0.0

        def _lis_val(c1: str, c2: str, col: str):
            row = lis_df.loc[(lis_df.chain1 == c1) & (lis_df.chain2 == c2), col]
            return row.values[0] if len(row) > 0 else (0.0 if col not in ("LIR", "cLIR") else "")

        def _pdq2_val(c1: str, c2: str) -> float:
            row = pdockq2_df.loc[(pdockq2_df.chain1 == c1) & (pdockq2_df.chain2 == c2), "pDockQ2"]
            return float(row.values[0]) if len(row) > 0 else 0.0

        pool_chains = sorted(chain_to_protein.keys())
        results: List[Dict[str, Any]] = []

        for i, chain_a in enumerate(pool_chains):
            for chain_b in pool_chains[i + 1:]:
                protein_a = chain_to_protein[chain_a]
                protein_b = chain_to_protein[chain_b]
                ppi_id = f"{protein_a}{ppi_separator}{protein_b}"

                mask_a = chain_ids == chain_a
                mask_b = chain_ids == chain_b

                idx_a = chain_to_idx[chain_a]
                idx_b = chain_to_idx[chain_b]
                iptm_pair = float(m.iptm_chain_pair[idx_a, idx_b])

                len_a = int(mask_a.sum())
                len_b = int(mask_b.sum())
                sc_iptm = InteractomeProcessor._size_correct_iptm(iptm_pair, len_a, len_b)

                pae_ab = m.pae[np.ix_(mask_a, mask_b)]
                pae_ba = m.pae[np.ix_(mask_b, mask_a)]

                lis_ab   = float(_lis_val(chain_a, chain_b, "LIS"))
                lis_ba   = float(_lis_val(chain_b, chain_a, "LIS"))
                lia_ab   = float(_lis_val(chain_a, chain_b, "LIA"))
                lia_ba   = float(_lis_val(chain_b, chain_a, "LIA"))
                clis_ab  = float(_lis_val(chain_a, chain_b, "cLIS"))
                clis_ba  = float(_lis_val(chain_b, chain_a, "cLIS"))
                clia_ab  = float(_lis_val(chain_a, chain_b, "cLIA"))
                clia_ba  = float(_lis_val(chain_b, chain_a, "cLIA"))
                ilis_ab  = float(_lis_val(chain_a, chain_b, "iLIS"))
                ilis_ba  = float(_lis_val(chain_b, chain_a, "iLIS"))
                ilia_ab  = float(_lis_val(chain_a, chain_b, "iLIA"))
                ilia_ba  = float(_lis_val(chain_b, chain_a, "iLIA"))
                ipsae_ab = _ipsae_val(chain_a, chain_b, "ipSAE")
                ipsae_ba = _ipsae_val(chain_b, chain_a, "ipSAE")

                results.append({
                    "PPI":        ppi_id,
                    "ORF_A":      protein_a,
                    "ORF_B":      protein_b,
                    "Path":       cif_str,
                    "ipTM":       iptm_pair,
                    "size_corrected_ipTM": sc_iptm,
                    "pTM_chain_A": float(m.iptm_chain_pair[idx_a][idx_a]),
                    "pTM_chain_B": float(m.iptm_chain_pair[idx_b][idx_b]),
                    "pLDDT_mean":     float(np.mean(m.cb_plddts)),
                    "pLDDT_mean_A":   float(np.mean(m.cb_plddts[mask_a])),
                    "pLDDT_mean_B":   float(np.mean(m.cb_plddts[mask_b])),
                    "pLDDT_median_A": float(np.median(m.cb_plddts[mask_a])),
                    "pLDDT_median_B": float(np.median(m.cb_plddts[mask_b])),
                    "pae_mean":    float(np.mean(m.pae)),
                    "pae_mean_A":  float(np.mean(m.pae[np.ix_(mask_a, mask_a)])),
                    "pae_mean_B":  float(np.mean(m.pae[np.ix_(mask_b, mask_b)])),
                    "pae_mean_AB": float(np.mean([np.mean(pae_ab), np.mean(pae_ba)])),
                    "pDockQ2_AB":  _pdq2_val(chain_a, chain_b),
                    "pDockQ2_BA":  _pdq2_val(chain_b, chain_a),
                    "LIS_AB":  lis_ab,  "LIS_BA":  lis_ba,
                    "LIA_AB":  lia_ab,  "LIA_BA":  lia_ba,
                    "cLIS_AB": clis_ab, "cLIS_BA": clis_ba,
                    "cLIA_AB": clia_ab, "cLIA_BA": clia_ba,
                    "iLIS_AB": ilis_ab, "iLIS_BA": ilis_ba,
                    "iLIA_AB": ilia_ab, "iLIA_BA": ilia_ba,
                    "Best_LIS":  float(max(lis_ab,  lis_ba)),
                    "Best_LIA":  float(max(lia_ab,  lia_ba)),
                    "Best_iLIS": float(max(ilis_ab, ilis_ba)),
                    "Best_iLIA": float(max(ilia_ab, ilia_ba)),
                    "LIR_AB":   _lis_val(chain_a, chain_b, "LIR"),
                    "cLIR_AB":  _lis_val(chain_a, chain_b, "cLIR"),
                    "ipSAE_AB":      ipsae_ab,
                    "ipSAE_BA":      ipsae_ba,
                    "max_ipSAE":     float(max(ipsae_ab, ipsae_ba)),
                    "ipSAE_d0chn_AB": _ipsae_val(chain_a, chain_b, "ipSAE_d0chn"),
                    "ipSAE_d0chn_BA": _ipsae_val(chain_b, chain_a, "ipSAE_d0chn"),
                    "ipSAE_d0dom_AB": _ipsae_val(chain_a, chain_b, "ipSAE_d0dom"),
                    "ipSAE_d0dom_BA": _ipsae_val(chain_b, chain_a, "ipSAE_d0dom"),
                })

        return results

    @classmethod
    def process_pooled(
        cls,
        pool_manifest_path: Union[str, Path],
        colabfold_output_dir: Union[str, Path],
        output_path: Union[str, Path],
        *,
        ppi_separator: str = "__",
    ) -> pd.DataFrame:
        """Process pooled ColabFold outputs into a single aggregated CSV.

        Reads ``pool_manifest.csv`` (written by
        :meth:`InteractomeWriter.write_pooled_jobs`), finds CIF files for
        each pool under ``colabfold_output_dir/{pool_id}/``, extracts
        pairwise metrics for every protein pair in each pool, and aggregates:

        - **Within a pool**: numeric columns are averaged over all CIF ranks.
        - **Across pools**: pairs appearing in multiple pools are averaged again;
          a ``n_pools`` column records how many pools contributed.

        The output schema matches ``interactome_data.csv`` produced by
        :meth:`process_models`, so :class:`InteractomeAnalyzer` can load it
        without changes.

        Parameters
        ----------
        pool_manifest_path : str or Path
            Path to ``pool_manifest.csv`` from :meth:`~InteractomeWriter.write_pooled_jobs`.
        colabfold_output_dir : str or Path
            Root directory of ColabFold outputs.  Expected structure after
            :func:`~virus_interactome.utils.reorganize_colabfold_outputs`::

                colabfold_output_dir/
                    pool_0000/
                        pool_0000_unrelaxed_rank_001_*.cif
                        ...
                    pool_0001/
                        ...

        output_path : str or Path
            Directory where ``interactome_data.csv`` is written.
        ppi_separator : str
            Separator used to build PPI identifiers. Defaults to ``'__'``.

        Returns
        -------
        pd.DataFrame
            Aggregated metrics, one row per unique protein pair.
        """
        manifest = pd.read_csv(pool_manifest_path)
        cf_dir = Path(colabfold_output_dir)
        out_dir = Path(output_path)
        out_dir.mkdir(parents=True, exist_ok=True)

        all_records: List[Dict[str, Any]] = []

        for _, row in manifest.iterrows():
            pool_id: str = str(row["pool_id"])
            proteins: List[str] = str(row["proteins"]).split(",")
            chain_letters = [chr(ord("A") + i) for i in range(len(proteins))]
            chain_to_protein: Dict[str, str] = dict(zip(chain_letters, proteins))

            pool_dir = cf_dir / pool_id
            if not pool_dir.exists():
                logger.warning(f"Pool directory not found, skipping: {pool_dir}")
                continue

            cif_files = sorted(pool_dir.glob("*.cif"))
            if not cif_files:
                logger.warning(f"No CIF files found in {pool_dir}, skipping.")
                continue

            # Collect per-model records for this pool
            pool_records: List[Dict[str, Any]] = []
            for cif_path in cif_files:
                try:
                    records = cls._process_pool_model(
                        cif_path, chain_to_protein, Engine.COLABFOLD, ppi_separator
                    )
                    for rec in records:
                        rec["pool_id"] = pool_id
                    pool_records.extend(records)
                except Exception as exc:
                    logger.error(f"Failed to process {cif_path}: {exc}")

            if not pool_records:
                continue

            # Average numeric columns over CIF ranks within this pool
            pool_df = pd.DataFrame(pool_records)
            str_cols = {"PPI", "ORF_A", "ORF_B", "Path", "pool_id", "LIR_AB", "cLIR_AB"}
            num_cols = [c for c in pool_df.columns if c not in str_cols]

            agg = pool_df.groupby("PPI")[num_cols].mean().reset_index()
            meta = pool_df.groupby("PPI")[["ORF_A", "ORF_B", "pool_id"]].first().reset_index()
            pool_avg = meta.merge(agg, on="PPI")
            all_records.append(pool_avg)

        if not all_records:
            logger.warning("process_pooled: no records produced.")
            return pd.DataFrame()

        combined = pd.concat(all_records, ignore_index=True)

        str_cols = {"PPI", "ORF_A", "ORF_B", "pool_id", "LIR_AB", "cLIR_AB"}
        num_cols = [c for c in combined.columns if c not in str_cols]

        agg_final = combined.groupby("PPI")[num_cols].mean().reset_index()
        n_pools = combined.groupby("PPI")["pool_id"].nunique().reset_index(name="n_pools")
        meta_final = combined.groupby("PPI")[["ORF_A", "ORF_B"]].first().reset_index()

        result = meta_final.merge(n_pools, on="PPI").merge(agg_final, on="PPI")
        result = result.round(4)

        out_csv = out_dir / "interactome_data.csv"
        result.to_csv(out_csv, index=False)
        logger.info(f"process_pooled: {len(result)} PPIs → {out_csv}")

        return result

    @staticmethod
    def _extract_monomer_plddt(
        cif_path: Path,
        engine: str,
    ) -> Dict[str, Any]:
        """
        Extracts pLDDT statistics from a single-chain (monomer) CIF file.

        Parameters
        ----------
        cif_path : Path
            Path to the monomer ``.cif`` model file.
        engine : str
            Engine that produced the file. One of ``'af3'``, ``'boltz'``, ``'boltz2'``,
            ``'colabfold'``.

        Returns
        -------
        dict
            Keys: ``plddt_mean``, ``plddt_median``, ``n_residues``.
            Values are ``np.nan`` if parsing fails.
        """
        nan_result: Dict[str, Any] = {
            "plddt_mean": np.nan,
            "plddt_median": np.nan,
            "n_residues": np.nan,
        }
        try:
            engine_norm = "boltz" if str(engine).lower() == "boltz2" else engine
            model  = Model(cif_path, engine=engine_norm)
            plddts = model._metrics.ca_plddts
            return {
                "plddt_mean":   float(np.mean(plddts)),
                "plddt_median": float(np.median(plddts)),
                "n_residues":   int(len(plddts)),
            }
        except Exception as exc:
            logger.warning(f"Could not extract pLDDT from {cif_path}: {exc}")
            return nan_result

    def process_monomers(
        self,
        output_path: Union[str, Path] = ".",
        prefix: str = "",
        **kwargs,
    ) -> pd.DataFrame:
        """
        Processes a list of monomer CIF files in parallel and writes a summary CSV.

        Extracts per-protein pLDDT statistics (mean, median) without computing
        interface metrics (ipSAE, LIS, etc.), which are undefined for monomers.
        Implements the same resume-logic as :meth:`process_models`: already-processed
        proteins are skipped on re-runs.

        Parameters
        ----------
        output_path : str or Path, optional
            Directory where ``monomer_data.csv`` is saved. Defaults to ``"."``.
        prefix : str, optional
            Substring stripped from folder names when parsing the protein ID.
            Defaults to ``""``.
        **kwargs
            Forwarded to :class:`concurrent.futures.ProcessPoolExecutor`
            (e.g. ``max_workers=4``).

        Returns
        -------
        pd.DataFrame
            DataFrame with columns:
            ``protein_id``, ``cif_path``, ``n_residues``,
            ``plddt_mean``, ``plddt_median``.
            Also written to ``{output_path}/monomer_data.csv``.

        Notes
        -----
        For AF3 monomers the default is 5 models per protein; for Boltz2, 1 model.
        Pass the appropriate ``model_list`` to :class:`InteractomeProcessor`
        accordingly.
        """
        import tqdm

        out_dir = Path(output_path)
        out_dir.mkdir(parents=True, exist_ok=True)
        monomer_csv = out_dir / "monomer_data.csv"

        existing_df = pd.DataFrame()
        models_to_process = self.model_paths.copy()

        # Resume logic: skip already-processed CIF paths
        if monomer_csv.exists():
            logger.info(f"Found existing data at {monomer_csv}. Resuming run...")
            existing_df = pd.read_csv(monomer_csv)
            if "cif_path" in existing_df.columns:
                processed = set(existing_df["cif_path"].astype(str))
                models_to_process = [
                    p for p in models_to_process if str(p) not in processed
                ]
                logger.info(
                    f"Skipping {len(self.model_paths) - len(models_to_process)} "
                    "already processed models."
                )

        if not models_to_process:
            logger.info("All monomer models already processed. Exiting.")
            return existing_df

        logger.info(f"Processing {len(models_to_process)} monomer models...")

        def _worker(cif_path: Path) -> Dict[str, Any]:
            dir_name = cif_path.parent.name
            protein_id = dir_name.replace(prefix, "")
            stats = InteractomeProcessor._extract_monomer_plddt(cif_path, self._engine)
            return {"protein_id": protein_id, "cif_path": str(cif_path), **stats}

        new_rows: list = []
        with concurrent.futures.ProcessPoolExecutor(**kwargs) as executor:
            for row in tqdm.tqdm(
                executor.map(_worker, models_to_process),
                total=len(models_to_process),
                desc="Processing Monomers",
            ):
                new_rows.append(row)

        new_df = pd.DataFrame(new_rows)
        final_df = pd.concat([existing_df, new_df], ignore_index=True)
        final_df = final_df.round(2)
        final_df.to_csv(monomer_csv, index=False)
        logger.info(f"Monomer data saved to {monomer_csv}")
        return final_df


