import os
import tqdm
import pandas as pd
import concurrent.futures

from sklearn.cluster import DBSCAN
from functools import partial

from .proteome_manager import ProteomeManager
from .molecule import MoleculeModel
from .metrics import calculate_all_metrics
from .plotting import plot_boxplots, plot_iptm_vs_ptm, plot_pae_clusters

class InteractomeProcessor:
    def __init__(self, model_list: list[str]):
        self.model_list = model_list
        self.df_het = None
        self.df_hom = None
        self.cluster_data = None

        self.process_models()
    
    def process_ppi(model_file: str, model_type: str = "AF3", prefix: str = "")-> tuple[dict, pd.DataFrame]:
        """
        Processes an AlphaFold3 CIF model file and extracts structural and confidence metrics.

        This function parses metadata from the CIF file path, loads associated JSON files containing
        summary confidences and full structural data, and computes various metrics such as pLDDT means,
        PAE means (overall and per chain), and clustering information from the PAE submatrix between chains.
        It also generates a cluster plot and returns both summary metrics and cluster details.

        Parameters
        ----------
        model_file : str
            Path to the CIF file generated by AlphaFold3 or Boltz2.

        Returns
        -------
        tuple
            A tuple containing:
            - A dictionary with summary metrics.
            - A DataFrame with cluster details.
        """
        # Parse metadata from the file path
        dir_name = os.path.dirname(model_file)
        base_name = os.path.basename(model_file).replace(".cif", "").replace(".pdb", "")
        folder_path = os.path.dirname(dir_name)
        ppi_id = os.path.basename(folder_path)
        model_number = int(base_name.split("_")[-1].replace("model_",""))

        # Create MoleculeModel instance
        if model_type == "AF3":
            molecule_model = MoleculeModel.from_af3(model_file)
        elif model_type == "boltz":
            molecule_model = MoleculeModel.from_boltz(model_file)
        
        # Calculate all metrics
        all_metrics = calculate_all_metrics(molecule_model)

        # Generate cluster plot
        plot_pae_clusters(molecule_model.pae, molecule_model.chain_by_res, output_path=dir_name, prefix=prefix)

        # Return summary metrics and cluster details
        return {"PPI": ppi_id, "ORF_A": ppi_id.split("_")[0], "ORF_B":ppi_id.split("_")[1], "Folder": folder_path, 
                "Model_num": model_number, 
                "iPTM": molecule_model.iptm, 
                "pTM": molecule_model.ptm, 
                # "chain_length_A": np.sum(chain_by_res == "A"), "chain_length_B":np.sum(chain_by_res == "B"), 
                **all_metrics
                }, all_metrics.get("cluster_info", pd.DataFrame())
    
    def process_models(self, output_path: str = ".", model_type: str = "AF3", prefix: str = "", **kwargs):
        ##Load output.csv and filter out processed data
        interactome_df = pd.DataFrame()
        clusters_df = pd.DataFrame()
        if os.path.exists(f'{output_path}/interactome_data.csv',):
            print("Loading existing data...")
            interactome_df = pd.read_csv(f'{output_path}/interactome_data.csv')
            folder_names = pd.Series([os.path.dirname(i) for i in all_ppi_models])
            all_ppi_models = all_ppi_models[~folder_names.isin(interactome_df.Folder)]
            clusters_df = pd.read_csv(f'{output_path}/clusters_data.csv')
    
        # Paralelización
        #List of tuples -> every tuple has list,df
        ##TODO: skip this is .csv exists
        interactome_df_list = []
        cluster_df_list = []
        # with concurrent.futures.ProcessPoolExecutor(max_workers=1) as executor:
        with concurrent.futures.ProcessPoolExecutor(**kwargs) as executor:
            worker = partial(process_ppi, model_type=model_type, prefix=prefix)
            # map devuelve los resultados en orden de la lista
            
            # all_args = [(model_file, model_type, prefix) for model_file in all_ppi_models]
            for res in tqdm.tqdm(executor.map(worker, all_ppi_models)): #For testing
            # for res in tqdm.tqdm(executor.map(process_ppi, all_args)): #For testing
                interactome_df_list.append(res[0])
                cluster_df_list.append(res[1])
        # Create the df with the info of all PPIs
        # interactome_df_list = [list[0] for list in results] 
        # interactome_df = pd.DataFrame(interactome_df_list,
        #                  columns=["PPI", "ORF_A", "ORF_B", "Folder", "Model_num","Fraction_disordered","iPTM","pTM",
        #                          "chain_lenght_A","chain_lenght_B", 
        #                          #    "contact_probs",
        #                          "plddt_mean", "plddt_mean_chain_A","plddt_mean_chain_B",
        #                          "mean_pae", "mean_pae_chain_A", "mean_pae_chain_B",
        #                          #    "min_pae_chain_A", "min_pae_chain_B",
        #                          "mean_pae_chain_A_B"])
        interactome_df = pd.concat([interactome_df, pd.DataFrame.from_dict(interactome_df_list)], ignore_index=True)
        # interactome_df = pd.DataFrame.from_dict(interactome_df_list)
        # interactome_df.reset_index(inplace=True, drop=True)

        # Join the dfs of the clusters in a single df
        # non_empty_cluster_info = filter(lambda x: len(x)>0, cluster_df_list)
        if len(cluster_df_list) > 0:
            filtered_cluster_df_list = [ i for i in cluster_df_list if i.shape[0]>0 ]
            clusters_df = pd.concat([clusters_df, pd.concat(filtered_cluster_df_list)], ignore_index=True)
        # clusters_df = pd.concat(non_empty_cluster_info, ignore_index=True)
        # clusters_df = pd.concat([df[1] for df in results], ignore_index=True)

        # Save dfs to .csv
        interactome_df.to_csv(f'{output_path}/interactome_data.csv', index=False)
        clusters_df.to_csv(f'{output_path}/clusters_data.csv', index=False)
        by_protein_df = get_info_for_proteins(interactome_df)
        by_protein_df.to_csv(f'{output_path}/interactome_data_by_protein.csv', index=False) 

        ## Plotting boxplots
        output_folder = f"{output_path}/plots"
        plddt_array, labels_array1 = process_boxplot_data(by_protein_df, "pLDDT_mean_ORF")
        pae_array, labels_array2 = process_boxplot_data(by_protein_df, "pae_mean_ORF")
        plot_boxplots("plddt",plddt_array, labels_array1, output_path=output_folder)
        plot_boxplots("pae",pae_array,labels_array2, output_path=output_folder)

        ## Plotting scatterplots
        plot_iptm_vs_ptm(interactome_df, output_path=output_folder)

class InteractomeWriter:
    def __init__(self, proteome_a: str | ProteomeManager, proteome_b: str | ProteomeManager | None = None):
        self.proteome_a = None
        self.proteome_b = None
        self.mode = "intra" # intra (intrainteractome) or inter (interactome between two proteomes)

        if isinstance(proteome_a, str):
            self.proteome_a = ProteomeManager(proteome_a)
        elif isinstance(proteome_a, ProteomeManager):
            self.proteome_a = proteome_a
        else:
            raise ValueError("proteome_a must be a string path or a ProteomeManager instance")
        
        if isinstance(proteome_b, str):
            self.proteome_b = ProteomeManager(proteome_b)
            self.mode = "inter"
        elif isinstance(proteome_b, ProteomeManager):
            self.proteome_b = proteome_b
            self.mode = "inter"
        else:
            self.mode = "intra"
    
    def write_af3_input(self, output_path: str = ".", prefix: str = "", batch_size: int = 30):
        pass

    def write_boltz_input(self, output_path: str = ".", prefix: str = ""):
        pass