import os
import logging
import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Optional, Any, Callable, Union
from pathlib import Path

from .plotting import (
    plot_confidence_landscape as _plot_confidence_landscape,
    plot_interactive_landscape as _plot_interactive_landscape,
)
from ._peptide_mixin import _PeptidePipelineMixin
from ._stats_mixin import _StatsMixin
from ._network_mixin import _NetworkMixin
from ._validation_mixin import _ValidationMixin

logger = logging.getLogger(__name__)


class InteractomeAnalyzer(_PeptidePipelineMixin, _StatsMixin, _NetworkMixin, _ValidationMixin):
    """
    Manages the loading, validation, and path manipulation of interactome analysis datasets.

    This class serves as a data manager that:
    1. Loads interactome and cluster CSV files generated by the InteractomeProcessor.
    2. Validates data integrity (checking for empty files and missing columns).
    3. Ensures consistency between datasets (e.g., matching PPI IDs).
    4. Handles path relocation, allowing analysis to be ported between different machines/folders.

    Attributes
    ----------
    output_path : Path
        Base directory for output generation.
    REQUIRED_INTERACTOME_COLS : list
        List of column names required in the interactome CSV ("PPI", "Folder").
    REQUIRED_CLUSTER_COLS : list
        List of column names required in the cluster CSV ("PPI", "path", "cluster_id").
    """
    REQUIRED_INTERACTOME_COLS = ["PPI", "Folder"]
    REQUIRED_CLUSTER_COLS = ["PPI", "path", "cluster_id"]

    _DEFAULT_INTERACTOME_FILENAME = "interactome_data.csv"
    _DEFAULT_CLUSTER_FILENAME = "clusters_data.csv"

    # Non-numeric columns excluded from rank aggregation across all mixins.
    _META_COLS: frozenset = frozenset({
        "PPI", "ORF_A", "ORF_B", "Folder", "Path",
        "LIR_AB", "cLIR_AB", "pool_id", "Tier", "LIS_Tier", "iLIS_Tier",
    })

    def _aggregate_per_ppi(
        self,
        model_agg: str = "mean",
        weight_col: Optional[str] = None,
    ) -> pd.DataFrame:
        """Collapse multiple model-rank rows into one row per PPI.

        Parameters
        ----------
        model_agg : str
            ``"mean"`` — average all numeric columns across ranks.
            ``"max"``  — take the per-column maximum across ranks.
            ``"best"`` — keep the single rank row with the highest ``weight_col``.
        weight_col : str, optional
            Required only for ``model_agg="best"``.

        Returns
        -------
        pd.DataFrame
            One row per unique PPI with string meta columns preserved and
            numeric columns aggregated.

        Raises
        ------
        RuntimeError
            If interactome data is not loaded.
        ValueError
            If ``model_agg`` is invalid or ``weight_col`` is missing for ``"best"``.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()

        if model_agg not in ("mean", "max", "best"):
            raise ValueError(f"model_agg must be 'mean', 'max', or 'best'. Got: '{model_agg}'")
        if model_agg == "best" and (weight_col is None or weight_col not in df.columns):
            raise ValueError(
                f"model_agg='best' requires a valid weight_col. Got: '{weight_col}'"
            )

        num_cols = [
            c for c in df.columns
            if c not in self._META_COLS and pd.api.types.is_numeric_dtype(df[c])
        ]
        meta_present = [c for c in df.columns if c != "PPI" and c not in num_cols]

        if model_agg == "best":
            return df.loc[df.groupby("PPI")[weight_col].idxmax()].reset_index(drop=True)

        meta = df.groupby("PPI")[meta_present].first().reset_index() if meta_present \
            else df.groupby("PPI")[[]].first().reset_index()
        agg_fn = df.groupby("PPI")[num_cols].mean() if model_agg == "mean" \
            else df.groupby("PPI")[num_cols].max()
        return meta.merge(agg_fn.reset_index(), on="PPI")

    def __init__(
        self,
        output_path: Union[str, Path] = ".",
        interactome_path: Optional[Union[str, Path]] = None,
        cluster_path: Optional[Union[str, Path]] = None,
    ):
        """
        Parameters
        ----------
        output_path : str or Path
            Base directory for output. When ``interactome_path`` / ``cluster_path``
            are not supplied, the constructor looks for the standard filenames
            (``interactome_data.csv``, ``clusters_data.csv``) inside this directory
            and loads them automatically if found.
        interactome_path : str or Path, optional
            Explicit path to the interactome CSV. Overrides auto-detection.
        cluster_path : str or Path, optional
            Explicit path to the cluster CSV. Overrides auto-detection.
        """
        self.output_path = Path(output_path)

        self._interactome_path: Optional[Path] = None
        self._interactome_data: Optional[pd.DataFrame] = None
        self._cluster_path: Optional[Path] = None
        self._cluster_data: Optional[pd.DataFrame] = None
        self._models_path: Optional[str] = None
        self._binder_data: Optional[pd.DataFrame] = None
        self._candidate_clusters: Optional[pd.DataFrame] = None

        if interactome_path is not None:
            self.interactome_path = Path(interactome_path)
        else:
            candidate = self.output_path / self._DEFAULT_INTERACTOME_FILENAME
            if candidate.exists():
                self.interactome_path = candidate

        if cluster_path is not None:
            self.cluster_path = Path(cluster_path)
        else:
            candidate = self.output_path / self._DEFAULT_CLUSTER_FILENAME
            if candidate.exists():
                self.cluster_path = candidate
    
    def get_confidence_tiers(
        self,
        ipsae_threshold: float = 0.5,
        pdockq2_threshold: float = 0.23,
        msa_threshold: int = 20,
        lis_threshold: float = 0.203,
        lia_threshold: float = 3432.0,
        ilis_threshold: float = 0.223,
    ) -> pd.DataFrame:
        """
        Categorizes interactome results into confidence tiers.

        Adds three independent tier columns:
          - ``Tier``      — ipSAE-based (original; Dunbrack 2025 + pDockQ2 + MSA depth).
          - ``LIS_Tier``  — LIS-based (Kim et al. 2024): Best LIS + Best LIA dual threshold.
          - ``iLIS_Tier`` — iLIS-based (Kim et al. 2025): single Best iLIS threshold.

        Parameters
        ----------
        ipsae_threshold : float, default=0.5
        pdockq2_threshold : float, default=0.23
        msa_threshold : int, default=20
        lis_threshold : float, default=0.203
            Best LIS threshold for LIS_Tier "High Confidence".
        lia_threshold : float, default=3432
            Best LIA threshold for LIS_Tier "High Confidence".
        ilis_threshold : float, default=0.223
            Best iLIS threshold for iLIS_Tier "High Confidence".

        Returns
        -------
        pd.DataFrame
            Interactome data with added ``Tier``, ``LIS_Tier``, and ``iLIS_Tier`` columns.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()

        # ── ipSAE-based tier (original) ──────────────────────────────────────
        ipsae_col   = "ipSAE_AB" if "ipSAE_AB" in df.columns else "ipSAE"
        pdockq2_col = "pDockQ2_AB" if "pDockQ2_AB" in df.columns else "pDockQ2"
        msa_col     = "msa_depth"

        if msa_col not in df.columns or df[msa_col].isna().all():
            logger.warning(
                "msa_depth is absent or all-NaN (expected for AF3/Boltz2). "
                "The MSA gate in Tier classification is inactive: all predictions "
                "pass the evolutionary-support criterion regardless of actual MSA coverage. "
                "Tier 1 counts may be inflated compared to ColabFold runs."
            )

        def _ipsae_classify(row) -> str:
            if ipsae_col not in row or pdockq2_col not in row:
                return "Unknown"
            msa_val     = row.get(msa_col, np.nan)
            ipsae_val   = row[ipsae_col]
            pdockq2_val = row[pdockq2_col]
            good_struct = ipsae_val > ipsae_threshold and pdockq2_val > pdockq2_threshold
            msa_ok      = pd.isna(msa_val) or msa_val > msa_threshold
            if good_struct and msa_ok:
                return "Tier 1 (High Confidence)"
            if good_struct and not msa_ok:
                return "Tier 2 (Specific/Novel)"
            if ipsae_val > ipsae_threshold and pdockq2_val <= pdockq2_threshold:
                return "Tier 3 (Weak/Dynamic)"
            return "Low Confidence"

        df["Tier"] = df.apply(_ipsae_classify, axis=1)

        # ── LIS-based tier (Kim et al. 2024) ─────────────────────────────────
        if "Best_LIS" in df.columns and "Best_LIA" in df.columns:
            def _lis_classify(row) -> str:
                if row["Best_LIS"] >= lis_threshold and row["Best_LIA"] >= lia_threshold:
                    return "High Confidence"
                if row["Best_LIS"] >= lis_threshold:
                    return "Low LIA"
                return "Low Confidence"
            df["LIS_Tier"] = df.apply(_lis_classify, axis=1)
        else:
            logger.warning(
                "Columns 'Best_LIS'/'Best_LIA' not found — LIS_Tier set to 'N/A'. "
                "Re-process models with the current metrics.py to generate them."
            )
            df["LIS_Tier"] = "N/A"

        # ── iLIS-based tier (Kim et al. 2025) ────────────────────────────────
        if "Best_iLIS" in df.columns:
            df["iLIS_Tier"] = df["Best_iLIS"].apply(
                lambda v: "High Confidence" if v >= ilis_threshold else "Low Confidence"
            )
        else:
            logger.warning(
                "Column 'Best_iLIS' not found — iLIS_Tier set to 'N/A'. "
                "Re-process models with the current metrics.py to generate them."
            )
            df["iLIS_Tier"] = "N/A"

        logger.info(
            f"Tier (ipSAE):\n{df['Tier'].value_counts()}\n"
            f"LIS_Tier:\n{df['LIS_Tier'].value_counts()}\n"
            f"iLIS_Tier:\n{df['iLIS_Tier'].value_counts()}"
        )
        return df

    def plot_confidence_landscape(
        self,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "Interactome Confidence Landscape",
    ) -> None:
        """Scatter plot of pDockQ2 vs ipSAE, sized by MSA depth, coloured by pLDDT."""
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded.")
        _plot_confidence_landscape(self._interactome_data, output_path=output_path, title=title)

    def plot_interactive_landscape(
        self,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "Interactome Confidence Landscape",
    ) -> None:
        """Interactive Plotly scatter of pDockQ2 vs ipSAE with hover PPI info."""
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded.")
        _plot_interactive_landscape(self._interactome_data, output_path=output_path, title=title)

    #Getters and setters

    # -------------------------------------------------------------------------
    # Binder Data
    # -------------------------------------------------------------------------
    
    @property
    def binder_data(self)-> Optional[pd.DataFrame]:
        """Peptide-protein candidate DataFrame set during pipeline execution."""
        return self._binder_data

    @binder_data.setter
    def binder_data(self, df: pd.DataFrame):
        """Set the binder candidate DataFrame directly."""
        self._binder_data = df

    # -------------------------------------------------------------------------
    # Interactome Data Management
    # -------------------------------------------------------------------------
    
    @property
    def interactome_path(self)-> Optional[Path]:
        """Path to the loaded interactome CSV file."""
        return self._interactome_path

    @property
    def interactome_data(self)-> Optional[pd.DataFrame]:
        """Loaded interactome DataFrame (None until ``interactome_path`` is set)."""
        return self._interactome_data 
    
    @interactome_path.setter
    def interactome_path(self, interactome_data_path: str):
        """
        Sets the interactome file path and triggers strict validation and loading.
        """

        path = Path(interactome_data_path)
        
        # 1. Existence Check
        if not path.exists():
            raise FileNotFoundError(f"Interactome file not found at: {path}")
        
        logger.info(f"Loading interactome data from {path}...")
        df = pd.read_csv(path)

        # 2. Empty Check
        if df.empty:
            raise ValueError(f"The interactome file {path} is empty. Cannot proceed.")
        
        # 3. Column Validation
        missing_cols = [c for c in self.REQUIRED_INTERACTOME_COLS if c not in df.columns]
        if missing_cols:
            raise ValueError(f"Interactome file invalid. Missing required columns: {missing_cols}")
        
        self._interactome_path = path

        self._interactome_data = df
        logger.info(f"Successfully loaded {len(df)} interactome records.")
    

    # -------------------------------------------------------------------------
    # Cluster Data Management
    # -------------------------------------------------------------------------
    
    @property
    def cluster_path(self)-> Optional[Path]:
        """Path to the loaded cluster CSV file."""
        return self._cluster_path

    @property
    def cluster_data(self)-> Optional[pd.DataFrame]:
        """Loaded cluster DataFrame (None until ``cluster_path`` is set)."""
        return self._cluster_data 
    
    @cluster_path.setter
    def cluster_path(self, cluster_data_path: Union[str, Path]):
        """
        Sets the cluster file path, loads data, validates it, and calculates the common root path.
        """
        path = Path(cluster_data_path)
        
        # 1. Existence Check
        if not path.exists():
            raise FileNotFoundError(f"Cluster file not found at: {path}")
        
        logger.info(f"Loading cluster data from {path}...")
        df = pd.read_csv(path)

        # 2. Empty Check
        if df.empty:
            raise ValueError(f"The cluster file {path} is empty.")

        # 3. Column Validation
        missing_cols = [c for c in self.REQUIRED_CLUSTER_COLS if c not in df.columns]
        if missing_cols:
            raise ValueError(f"Cluster file invalid. Missing required columns: {missing_cols}")
        
        # 4. Consistency Check
        if self._interactome_data is not None:
            interactome_ppis = set(self._interactome_data["PPI"])
            cluster_ppis = set(df["PPI"])
            orphans = cluster_ppis - interactome_ppis
            
            if orphans:
                logger.warning(f"Consistency Warning: Found {len(orphans)} PPI IDs in clusters "
                               f"that are NOT present in the interactome data.")
        
        # 5. Determine Common Path (Logic for _models_path)
        # We try to find the common prefix of all paths to establish the 'models_path'
        if "path" in df.columns:
            # Drop NAs and convert to list
            paths = df["path"].dropna().tolist()
            if paths:
                try:
                    self._models_path = os.path.commonpath(paths)
                    logger.info(f"Detected common models root path: {self._models_path}")
                except ValueError as e:
                    logger.warning(f"Could not automatically determine common path: {e}")
                    self._models_path = ""        
        
        self._cluster_path = path

        self._cluster_data = df
       
    @property
    def models_path(self)-> Optional[str]:
        """Common root directory for model ``.cif`` files."""
        return self._models_path 

    @models_path.setter
    def models_path(self, new_model_path: str):
        """
        Updates the root directory for models across all loaded datasets.
        Useful when moving analysis to a new machine.
        """
        if self._cluster_data is None or self._interactome_data is None:
            raise RuntimeError("Cannot update models_path: Data not loaded. Set interactome_path and cluster_path first.")
        
        old_path = self._models_path if self._models_path else ""
        logger.info(f"Relocating models: replacing '{old_path}' with '{new_model_path}'")
        
        # Update Cluster Data (regex=False: treat path separators as literals)
        if "path" in self._cluster_data.columns:
            self._cluster_data["path"] = self._cluster_data["path"].astype(str).str.replace(old_path, new_model_path, regex=False)

        # Update Interactome Data
        if "Folder" in self._interactome_data.columns:
            self._interactome_data["Folder"] = self._interactome_data["Folder"].astype(str).str.replace(old_path, new_model_path, regex=False)
        
        self._models_path = new_model_path
        logger.info(f"Path relocation complete. New root: {self._models_path}")
       
        return self._cluster_path 

    def __str__(self)-> str:
        """Returns a summary of the loaded data status."""
        interactome_state = str(self._interactome_path) if self._interactome_path else "Not Loaded"
        interactome_len = len(self._interactome_data) if self._interactome_data is not None else 0
        
        cluster_state = str(self._cluster_path) if self._cluster_path else "Not Loaded"
        cluster_len = len(self._cluster_data) if self._cluster_data is not None else 0
        
        return f"""<InteractomeAnalyzer>
        ---------------------------
        Interactome: {interactome_state}
        Records:     {interactome_len}
        ---------------------------
        Clusters:    {cluster_state}
        Records:     {cluster_len}
        ---------------------------
        """
    
    def __len__(self)-> int:
        """Return the number of PPI rows in the loaded interactome (0 if not loaded)."""
        if self._interactome_data is not None:
            return len(self._interactome_data)
        return 0
    
