import os
import logging
import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Optional, Any, Callable, Union
from pathlib import Path
from moleculekit.molecule import Molecule

from .databases import DatabaseClient
from .plotting import (
    plot_confidence_landscape as _plot_confidence_landscape,
    plot_interactive_landscape as _plot_interactive_landscape,
    plot_network as _plot_network_figure,
)

logger = logging.getLogger(__name__)


class InteractomeAnalyzer:
    """
    Manages the loading, validation, and path manipulation of interactome analysis datasets.

    This class serves as a data manager that:
    1. Loads interactome and cluster CSV files generated by the InteractomeProcessor.
    2. Validates data integrity (checking for empty files and missing columns).
    3. Ensures consistency between datasets (e.g., matching PPI IDs).
    4. Handles path relocation, allowing analysis to be ported between different machines/folders.

    Attributes
    ----------
    output_path : Path
        Base directory for output generation.
    REQUIRED_INTERACTOME_COLS : list
        List of column names required in the interactome CSV ("PPI", "Folder").
    REQUIRED_CLUSTER_COLS : list
        List of column names required in the cluster CSV ("PPI", "path", "cluster_id").
    """
    REQUIRED_INTERACTOME_COLS = ["PPI", "Folder"]
    REQUIRED_CLUSTER_COLS = ["PPI", "path", "cluster_id"]
    
    def __init__(self, output_path : Union[str, Path] = "."):
        """
        Initializes the Analyzer with a default output path.

        Parameters
        ----------
        output_path : str or Path, optional
            The directory where results will be saved. Defaults to current directory (".").
        """
        self.output_path = Path(output_path)
        
        self._interactome_path: Optional[Path] = None
        self._interactome_data: Optional[pd.DataFrame] = None
        self._cluster_path: Optional[Path] = None
        self._cluster_data: Optional[pd.DataFrame] = None
        self._models_path: Optional[str] = None
        self._binder_data: Optional[pd.DataFrame] = None
        self._candidate_clusters: Optional[pd.DataFrame] = None
    
    def get_confidence_tiers(
        self,
        ipsae_threshold: float = 0.5,
        pdockq2_threshold: float = 0.23,
        msa_threshold: int = 20,
        lis_threshold: float = 0.203,
        lia_threshold: float = 3432.0,
        ilis_threshold: float = 0.223,
    ) -> pd.DataFrame:
        """
        Categorizes interactome results into confidence tiers.

        Adds three independent tier columns:
          - ``Tier``      — ipSAE-based (original; Dunbrack 2025 + pDockQ2 + MSA depth).
          - ``LIS_Tier``  — LIS-based (Kim et al. 2024): Best LIS + Best LIA dual threshold.
          - ``iLIS_Tier`` — iLIS-based (Kim et al. 2025): single Best iLIS threshold.

        Parameters
        ----------
        ipsae_threshold : float, default=0.5
        pdockq2_threshold : float, default=0.23
        msa_threshold : int, default=20
        lis_threshold : float, default=0.203
            Best LIS threshold for LIS_Tier "High Confidence".
        lia_threshold : float, default=3432
            Best LIA threshold for LIS_Tier "High Confidence".
        ilis_threshold : float, default=0.223
            Best iLIS threshold for iLIS_Tier "High Confidence".

        Returns
        -------
        pd.DataFrame
            Interactome data with added ``Tier``, ``LIS_Tier``, and ``iLIS_Tier`` columns.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()

        # ── ipSAE-based tier (original) ──────────────────────────────────────
        ipsae_col   = "ipSAE_AB" if "ipSAE_AB" in df.columns else "ipSAE"
        pdockq2_col = "pDockQ2_AB" if "pDockQ2_AB" in df.columns else "pDockQ2"
        msa_col     = "msa_depth"

        def _ipsae_classify(row) -> str:
            if ipsae_col not in row or pdockq2_col not in row:
                return "Unknown"
            msa_val     = row.get(msa_col, np.nan)
            ipsae_val   = row[ipsae_col]
            pdockq2_val = row[pdockq2_col]
            good_struct = ipsae_val > ipsae_threshold and pdockq2_val > pdockq2_threshold
            msa_ok      = pd.isna(msa_val) or msa_val > msa_threshold
            if good_struct and msa_ok:
                return "Tier 1 (High Confidence)"
            if good_struct and not msa_ok:
                return "Tier 2 (Specific/Novel)"
            if ipsae_val > ipsae_threshold and pdockq2_val <= pdockq2_threshold:
                return "Tier 3 (Weak/Dynamic)"
            return "Low Confidence"

        df["Tier"] = df.apply(_ipsae_classify, axis=1)

        # ── LIS-based tier (Kim et al. 2024) ─────────────────────────────────
        if "Best_LIS" in df.columns and "Best_LIA" in df.columns:
            def _lis_classify(row) -> str:
                if row["Best_LIS"] >= lis_threshold and row["Best_LIA"] >= lia_threshold:
                    return "High Confidence"
                if row["Best_LIS"] >= lis_threshold:
                    return "Low LIA"
                return "Low Confidence"
            df["LIS_Tier"] = df.apply(_lis_classify, axis=1)
        else:
            logger.warning(
                "Columns 'Best_LIS'/'Best_LIA' not found — LIS_Tier set to 'N/A'. "
                "Re-process models with the current metrics.py to generate them."
            )
            df["LIS_Tier"] = "N/A"

        # ── iLIS-based tier (Kim et al. 2025) ────────────────────────────────
        if "Best_iLIS" in df.columns:
            df["iLIS_Tier"] = df["Best_iLIS"].apply(
                lambda v: "High Confidence" if v >= ilis_threshold else "Low Confidence"
            )
        else:
            logger.warning(
                "Column 'Best_iLIS' not found — iLIS_Tier set to 'N/A'. "
                "Re-process models with the current metrics.py to generate them."
            )
            df["iLIS_Tier"] = "N/A"

        logger.info(
            f"Tier (ipSAE):\n{df['Tier'].value_counts()}\n"
            f"LIS_Tier:\n{df['LIS_Tier'].value_counts()}\n"
            f"iLIS_Tier:\n{df['iLIS_Tier'].value_counts()}"
        )
        return df

    def plot_confidence_landscape(
        self,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "Interactome Confidence Landscape",
    ) -> None:
        """Scatter plot of pDockQ2 vs ipSAE, sized by MSA depth, coloured by pLDDT."""
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded.")
        _plot_confidence_landscape(self._interactome_data, output_path=output_path, title=title)

    def plot_interactive_landscape(
        self,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "Interactome Confidence Landscape",
    ) -> None:
        """Interactive Plotly scatter of pDockQ2 vs ipSAE with hover PPI info."""
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded.")
        _plot_interactive_landscape(self._interactome_data, output_path=output_path, title=title)

    #Getters and setters

    # -------------------------------------------------------------------------
    # Binder Data
    # -------------------------------------------------------------------------
    
    @property
    def binder_data(self)-> Optional[pd.DataFrame]:
        """Peptide-protein candidate DataFrame set during pipeline execution."""
        return self._binder_data

    @binder_data.setter
    def binder_data(self, df: pd.DataFrame):
        """Set the binder candidate DataFrame directly."""
        self._binder_data = df

    # -------------------------------------------------------------------------
    # Interactome Data Management
    # -------------------------------------------------------------------------
    
    @property
    def interactome_path(self)-> Optional[Path]:
        """Path to the loaded interactome CSV file."""
        return self._interactome_path

    @property
    def interactome_data(self)-> Optional[pd.DataFrame]:
        """Loaded interactome DataFrame (None until ``interactome_path`` is set)."""
        return self._interactome_data 
    
    @interactome_path.setter
    def interactome_path(self, interactome_data_path: str):
        """
        Sets the interactome file path and triggers strict validation and loading.
        """

        path = Path(interactome_data_path)
        
        # 1. Existence Check
        if not path.exists():
            raise FileNotFoundError(f"Interactome file not found at: {path}")
        
        logger.info(f"Loading interactome data from {path}...")
        df = pd.read_csv(path)

        # 2. Empty Check
        if df.empty:
            raise ValueError(f"The interactome file {path} is empty. Cannot proceed.")
        
        # 3. Column Validation
        missing_cols = [c for c in self.REQUIRED_INTERACTOME_COLS if c not in df.columns]
        if missing_cols:
            raise ValueError(f"Interactome file invalid. Missing required columns: {missing_cols}")
        
        self._interactome_path = path

        self._interactome_data = df
        logger.info(f"Successfully loaded {len(df)} interactome records.")
    

    # -------------------------------------------------------------------------
    # Cluster Data Management
    # -------------------------------------------------------------------------
    
    @property
    def cluster_path(self)-> Optional[Path]:
        """Path to the loaded cluster CSV file."""
        return self._cluster_path

    @property
    def cluster_data(self)-> Optional[pd.DataFrame]:
        """Loaded cluster DataFrame (None until ``cluster_path`` is set)."""
        return self._cluster_data 
    
    @cluster_path.setter
    def cluster_path(self, cluster_data_path: Union[str, Path]):
        """
        Sets the cluster file path, loads data, validates it, and calculates the common root path.
        """
        path = Path(cluster_data_path)
        
        # 1. Existence Check
        if not path.exists():
            raise FileNotFoundError(f"Cluster file not found at: {path}")
        
        logger.info(f"Loading cluster data from {path}...")
        df = pd.read_csv(path)

        # 2. Empty Check
        if df.empty:
            raise ValueError(f"The cluster file {path} is empty.")

        # 3. Column Validation
        missing_cols = [c for c in self.REQUIRED_CLUSTER_COLS if c not in df.columns]
        if missing_cols:
            raise ValueError(f"Cluster file invalid. Missing required columns: {missing_cols}")
        
        # 4. Consistency Check
        if self._interactome_data is not None:
            interactome_ppis = set(self._interactome_data["PPI"])
            cluster_ppis = set(df["PPI"])
            orphans = cluster_ppis - interactome_ppis
            
            if orphans:
                logger.warning(f"Consistency Warning: Found {len(orphans)} PPI IDs in clusters "
                               f"that are NOT present in the interactome data.")
        
        # 5. Determine Common Path (Logic for _models_path)
        # We try to find the common prefix of all paths to establish the 'models_path'
        if "path" in df.columns:
            # Drop NAs and convert to list
            paths = df["path"].dropna().tolist()
            if paths:
                try:
                    self._models_path = os.path.commonpath(paths)
                    logger.info(f"Detected common models root path: {self._models_path}")
                except ValueError as e:
                    logger.warning(f"Could not automatically determine common path: {e}")
                    self._models_path = ""        
        
        self._cluster_path = path

        self._cluster_data = df
       
    @property
    def models_path(self)-> Optional[str]:
        """Common root directory for model ``.cif`` files."""
        return self._models_path 

    @models_path.setter
    def models_path(self, new_model_path: str):
        """
        Updates the root directory for models across all loaded datasets.
        Useful when moving analysis to a new machine.
        """
        if self._cluster_data is None or self._interactome_data is None:
            raise RuntimeError("Cannot update models_path: Data not loaded. Set interactome_path and cluster_path first.")
        
        old_path = self._models_path if self._models_path else ""
        logger.info(f"Relocating models: replacing '{old_path}' with '{new_model_path}'")
        
        # Update Cluster Data (regex=False: treat path separators as literals)
        if "path" in self._cluster_data.columns:
            self._cluster_data["path"] = self._cluster_data["path"].astype(str).str.replace(old_path, new_model_path, regex=False)

        # Update Interactome Data
        if "Folder" in self._interactome_data.columns:
            self._interactome_data["Folder"] = self._interactome_data["Folder"].astype(str).str.replace(old_path, new_model_path, regex=False)
        
        self._models_path = new_model_path
        logger.info(f"Path relocation complete. New root: {self._models_path}")
       
        return self._cluster_path 

    def __str__(self)-> str:
        """Returns a summary of the loaded data status."""
        interactome_state = str(self._interactome_path) if self._interactome_path else "Not Loaded"
        interactome_len = len(self._interactome_data) if self._interactome_data is not None else 0
        
        cluster_state = str(self._cluster_path) if self._cluster_path else "Not Loaded"
        cluster_len = len(self._cluster_data) if self._cluster_data is not None else 0
        
        return f"""<InteractomeAnalyzer>
        ---------------------------
        Interactome: {interactome_state}
        Records:     {interactome_len}
        ---------------------------
        Clusters:    {cluster_state}
        Records:     {cluster_len}
        ---------------------------
        """
    
    def __len__(self)-> int:
        """Return the number of PPI rows in the loaded interactome (0 if not loaded)."""
        if self._interactome_data is not None:
            return len(self._interactome_data)
        return 0
    
    def run_full_pipeline(self, ipsae_filter: Optional[float] = None, **kwargs):
        """
        Executes the complete analysis pipeline.

        Parameters
        ----------
        ipsae_filter : float, optional
            If provided, logs how many PPIs are above this confidence threshold.
            Structural analysis will proceed for ALL candidates regardless.
        **kwargs
            Arguments passed to downstream methods:
            - cluster_ratio_threshold (float, default=7.0)
            - min_peptide_len (int, default=5)
        """
        if self._cluster_data is None:
            logger.warning("Cannot run pipeline: Cluster data is missing.")
            return
        
        logger.info("Starting peptide-protein analysis pipeline...")
        
        # Default cluster ratio for peptides set to 7.0 as requested
        kwargs.setdefault('cluster_ratio_threshold', 7.0)

        # Log filtering info if requested, but DO NOT filter the structural pipeline
        if ipsae_filter is not None and self._interactome_data is not None:
            df = self._interactome_data
            ipsae_col = None
            for col in ["ipSAE_d0dom_AB", "ipSAE_d0_dom_AB", "ipSAE_AB", "ipSAE"]:
                if col in df.columns:
                    ipsae_col = col
                    break

            if ipsae_col:
                high_conf_ppis = df[df[ipsae_col] > ipsae_filter]["PPI"].unique()
                logger.info(f"Report: {len(high_conf_ppis)} PPIs are above {ipsae_col} > {ipsae_filter}.")
        
        # Run structural analysis for ALL candidates
        self.analyze_peptide_proteins_pairs(**kwargs)
    
    def _get_candidate_clusters(self, cluster_ratio_threshold: float = 5.0, 
                                min_peptide_len: int = 5)-> pd.DataFrame:
        """
        Identifies candidate peptide-protein interactions based on cluster geometry.

        Filters clusters that have a high aspect ratio (elongated shape), suggesting 
        a peptide binding to a larger protein surface. It determines which chain 
        corresponds to the 'Binder' (protein) and which to the 'Peptide' based on 
        the dimensions of the interaction interface.

        Parameters
        ----------
        cluster_ratio_threshold : float, optional
            The minimum aspect ratio (max_side / min_side) required to consider 
            a cluster as a peptide candidate. Defaults to 5.0.
        min_peptide_len : int, optional
            The minimum length (in residues) of the interface to be considered valid. 
            Defaults to 5.

        Returns
        -------
        pd.DataFrame
            A DataFrame containing candidate clusters with additional columns:
            - Binder_name, Binder_chain, Binder_start, Binder_end
            - Peptide_name, Peptide_chain, Peptide_start, Peptide_end
        """
        # 1. Validate Data Availability
        if self._cluster_data is None or self._cluster_data.empty:
            logger.warning("Cluster data is empty. No candidates to process.")
            return pd.DataFrame()

        #Generate a copy of the df with candidate clusters
        df = self._cluster_data.copy()

        # 2. Handle Legacy Column Naming (Cluster_ratio vs cluster_ratio)
        ratio_col = "cluster_ratio" if "cluster_ratio" in df.columns else "Cluster_ratio"
        
        # 3. Apply Filters (Geometry & Thresholds)
        # Ensure dimensions are positive and ratio meets threshold
        mask = (
            (df["x_len"] > 0) & 
            (df["y_len"] > 0) & 
            (df[ratio_col] > cluster_ratio_threshold) & 
            (df["x_len"] >= min_peptide_len) & 
            (df["y_len"] >= min_peptide_len)
        )
        candidate_clusters = df[mask].copy()

        # 4. Process Candidates (Identify Binder vs Peptide)
        new_cols = {
            "Binder_chain": [], "Binder_name": [], "Binder_start": [], "Binder_end": [],
            "Peptide_chain": [], "Peptide_name": [], "Peptide_start": [], "Peptide_end": []
        }

        for _, row in candidate_clusters.iterrows():
            # Robust split (take first two elements only) to handle names like "GenA__GenB__v2"
            parts = row["PPI"].split("__")
            if len(parts) >= 2:
                orf_a, orf_b = parts[:2]
            else:
                # Fallback for malformed PPI IDs
                orf_a, orf_b = row["PPI"], ""

            # Logic: Assign roles based on dimensions
            # If X dimension > Y dimension -> Chain A is Binder, Chain B is Peptide
            
            if row["x_len"] > row["y_len"]:
                # X is longer
                new_cols["Binder_chain"].append("A")
                new_cols["Peptide_chain"].append("B")
                new_cols["Peptide_start"].append(int(row["y_min"]))
                new_cols["Peptide_end"].append(int(row["y_max"]))
                new_cols["Binder_start"].append(int(row["x_min"]))
                new_cols["Binder_end"].append(int(row["x_max"]))
                new_cols["Binder_name"].append(orf_a)
                new_cols["Peptide_name"].append(orf_b)
            else:
                # Y is longer
                new_cols["Binder_chain"].append("B")
                new_cols["Peptide_chain"].append("A")
                new_cols["Peptide_start"].append(int(row["x_min"]))
                new_cols["Peptide_end"].append(int(row["x_max"]))
                new_cols["Binder_start"].append(int(row["y_min"]))
                new_cols["Binder_end"].append(int(row["y_max"]))
                new_cols["Binder_name"].append(orf_b)
                new_cols["Peptide_name"].append(orf_a)
        
        # 5. Assign new columns to DataFrame
        for col_name, data_list in new_cols.items():
            candidate_clusters[col_name] = data_list
        
        
        # Return with a clean index
        return candidate_clusters.reset_index(drop=True)

    def _curate_protein_peptide_models(self, data: pd.Series)-> Molecule:
        """
        Loads a PDB model and standardizes chain identifiers for analysis.

        This method ensures a consistent schema where:
        1. Chain A represents the 'Binder' (Protein).
        2. Chain B represents the 'Peptide'.
        3. Only the interface residues of the peptide are kept.

        Parameters
        ----------
        data : pd.Series
            A row from the candidate clusters DataFrame containing:
            - "path": Path to the PDB file.
            - "Peptide_chain": Original chain ID of the peptide ('A' or 'B').
            - "Peptide_start": Start residue index of the peptide interface.
            - "Peptide_end": End residue index of the peptide interface.

        Returns
        -------
        Molecule
            A MoleculeKit object with standardized chains and filtered atoms.
        """
        # Extract and cast types
        mol_path = str(data["path"])
        peptide_chain = str(data["Peptide_chain"])
        peptide_start = int(data["Peptide_start"])
        peptide_end = int(data["Peptide_end"])

        mol = Molecule(mol_path)

        # Standardize: Binder -> A, Peptide -> B
        if peptide_chain == "A":
            # Swap logic using temporary chain 'C'
            mol.set("chain", "C", "chain A") # Peptide(A) -> C
            mol.set("chain", "A", "chain B") # Binder(B) -> A
            mol.set("chain", "B", "chain C") # Peptide(C) -> B
       
        # Filter: Keep Binder (A) or Peptide (B) within interface range
        mol.filter(f"(chain A) or (chain B and resid {peptide_start} to {peptide_end})")
        return mol
    
    
             
    def _create_binder_alignments(self, 
                                  model_to_align: str, 
                                  reference_model: Union[str, Molecule])-> Molecule:
        """
        Aligns a target protein model to a reference structure based on the Binder (Chain A).

        This method performs a structural alignment using the following steps:
        1. Loads the target model.
        2. Filters the target's Chain A to keep only residues present in the reference 
           (ensuring a valid index-based alignment).
        3. Preserves Chain B (Peptide) entirely.
        4. Aligns the filtered target to the reference.

        Parameters
        ----------
        model_to_align : str
            Path to the PDB file of the model to be aligned.
        reference_model : str or Molecule
            The reference structure used as the fixed point. Can be a file path 
            (str) or a loaded Molecule object.

        Returns
        -------
        Molecule
            The aligned Molecule object (containing filtered Chain A + Chain B).
        """
        # 1. Resolve Reference Model (Path vs Object)
        if isinstance(reference_model, str):
            reference_mol = Molecule(reference_model)
        elif isinstance(reference_model, Molecule):
            reference_mol = reference_model
        else:
            raise ValueError("reference_model should be a path (str) or a Molecule instance")
        
        # 2. Get Reference Residues
        residues_in_reference_chain = reference_mol.resid.astype(str)
        reference_resid_str = ' '.join(residues_in_reference_chain)
        
        # 3. Load Target Model
        tmp_mol = Molecule(model_to_align)
        
        # 4. Filter Target
        # Keep Chain A (only matching reference residues) OR Chain B (Peptide)
        tmp_mol.filter(f"(chain A and resid {reference_resid_str}) or (chain B)")
        
        # 5. Align
        # mode="index" requires strict atom-to-atom correspondence.
        tmp_mol.align(f"chain A",
                    refmol=reference_mol,
                    refsel=f"chain A",
                    mode="index"
                    )
        return tmp_mol
    
    def _get_reference_structure_for_binder(self, all_structs: List[str]) -> Molecule:
        """
        Selects the best structural model to serve as a reference for alignment.

        The selection relies on the pLDDT score.
        It selects the model with the highest median pLDDT for Chain A (Binder)
        and trims it to keep only the high-confidence residues (pLDDT > 70).

        Parameters
        ----------
        all_structs : List[str]
            A list of file paths to the PDB models.

        Returns
        -------
        Molecule
            A MoleculeKit object of the reference binder, containing only 
            Chain A residues with high structural confidence.
        """
        # Load all molecules
        mol_list = [ Molecule(i) for i in all_structs]
        
        plddt_scores = []
        for mol in mol_list:
            # Select Chain A (Binder)
            # numpy boolean masking on the 'chain' attribute
            mask_a = mol.chain == "A"
            if np.any(mask_a):
                plddt_chain_A = mol.beta[mask_a]
                score = np.median(plddt_chain_A)
            else:
                score = 0.0 # Fallback if chain A is missing
            plddt_scores.append(score)
        
        plddt_scores = np.array(plddt_scores)

        # Select the best index (Highest median pLDDT) 
        best_global_idx = np.argmax(plddt_scores)

        # Define the reference molecule, just one by binder
        reference_mol = mol_list[best_global_idx].copy()
        
        # 1. Filter: Keep only Chain A
        reference_mol.filter("chain A")

        # 2. Filter: Keep only high confidence residues (pLDDT > 70)
        # Get Residue IDs of CA atoms where Beta > 70
        # We use CA atoms as representative for the whole residue to avoid duplicates
        mask_ca = reference_mol.name == "CA"
        
        # Two-step masking: 
        # 1. Get betas for CAs. 
        # 2. Check which are > 70.
        # 3. Apply that boolean mask to the resids of CAs.
        high_conf_mask = reference_mol.beta[mask_ca] > 70
        reference_resids = reference_mol.resid[mask_ca][high_conf_mask]
        
        # Create selection string
        reference_resids = reference_resids.astype(str)
        reference_resid_str = ' '.join(reference_resids)

        # Apply final filter
        if reference_resid_str:
            reference_mol.filter(f"resid {reference_resid_str}")
        else:
            logger.warning("No high-confidence residues (pLDDT > 70) found in best model. Returning full Chain A.")
        
        return reference_mol

    def analyze_peptide_proteins_pairs(self, **kwargs):
        """
        Executes the structural analysis pipeline for peptide-protein interactions.
        ...
        """
        # 1. Setup Directories
        output_path = f"{self.output_path}/prot_peptide"
        os.makedirs(output_path, exist_ok=True)

        # Extract filtering arguments intended for _get_candidate_clusters
        filter_args = {
            'cluster_ratio_threshold': kwargs.pop('cluster_ratio_threshold', 5.0),
            'min_peptide_len': kwargs.pop('min_peptide_len', 5)
        }

        # 2. Identify Candidates
        self._candidate_clusters = self._get_candidate_clusters(**filter_args)

        if self._candidate_clusters is None or self._candidate_clusters.empty:
            logger.warning("No candidate peptide-protein clusters found. Skipping analysis.")
            return
        
        # Create folder structure for each unique binder
        for binder in self._candidate_clusters.Binder_name.unique():
            os.makedirs(f"{output_path}/{binder}/", exist_ok=True)
            os.makedirs(f"{output_path}/{binder}/filtered/", exist_ok=True)
            os.makedirs(f"{output_path}/{binder}/aligned/", exist_ok=True)
        
        # 3. Prepare Working DataFrame
        cols = ["PPI", "model_num", "x_len", "y_len", 
                "Binder_name", "Binder_chain", "Binder_start", "Binder_end",
                "Peptide_name", "Peptide_chain", "Peptide_start", "Peptide_end", "path"]
        
        df = self._candidate_clusters.loc[:,cols].copy()
        
        # Generate Unique IDs (PPI + Model + ClusterID)
        df.loc[: , "PPI"] = df.PPI + "_" +  self._candidate_clusters.model_num.astype(str) + "_" + self._candidate_clusters.cluster_id.astype(str)
        
        # 4. Filtering Loop (Curate Structures)
        filtered_names = []
        for idx, row in df.iterrows():
            output_name = f"{output_path}/{row.Binder_name}/filtered/{row.PPI}.pdb"
            filtered_names.append(output_name)
            
            if not os.path.exists(output_name):
                mol = self._curate_protein_peptide_models(row)
                mol.write(output_name)
            else:
                logger.info(f"Skipping {output_name}, already filtered...")
        df.loc[:, "filtered_path"] = filtered_names
        
        # 5. Analysis Loop per Binder
        binder_df = pd.DataFrame()
        
        for binder in self._candidate_clusters.Binder_name.unique():

            ppi_data = df.loc[self._candidate_clusters.Binder_name == binder,:].copy()
            all_structs = ppi_data.filtered_path.values
            
            if len(all_structs) == 0:
                logger.warning(f"No valid models for binder {binder} after filtering. Skipping...")
                continue

            # A. Get/Create Reference Structure
            reference_output_name = f"{output_path}/{binder}/reference_{binder}.pdb"
            if not os.path.exists(reference_output_name):
                reference_molecule = self._get_reference_structure_for_binder(all_structs)
                reference_molecule.write(reference_output_name)
            else:
                reference_molecule = Molecule(reference_output_name)
                logger.info(f"Skipping reference generation for {binder}, exists...")

            # B. Alignment Loop
            aligned_models = []
            for tmp_mol_name in all_structs:

                # Simple string replacement for path (assumes standard folder structure)
                tmp_mol_name_aligned = tmp_mol_name.replace("filtered", "aligned")
                
                if not os.path.exists(tmp_mol_name_aligned):
                    tmp_mol = self._create_binder_alignments(tmp_mol_name, reference_molecule)
                    tmp_mol.write(tmp_mol_name_aligned)
                else:
                    logger.debug(f"Skipping alignment for {tmp_mol_name_aligned}...")
                
                aligned_models.append(tmp_mol_name_aligned)

            # C. Clustering (DBSCAN)
            tmp_df, cluster_info = self.cluster_protein_peptides(aligned_models, reference_output_name, **kwargs)
            
            if tmp_df.empty or len(cluster_info.get("cluster_labels", [])) == 0:
                logger.warning(f"No spatial clusters found for {binder}. Skipping ChimeraX generation.")
                continue

            tmp_df.insert(0, "Binder", binder)
            binder_df = pd.concat([binder_df, tmp_df], ignore_index=True)

            # D. Visualization Preparation (ChimeraX)
            # Ensure lengths match before assignment
            labels = cluster_info.get("cluster_labels")
            centers = cluster_info.get("peptide_centers")

            if len(labels) == len(ppi_data):
                ppi_data.loc[:, "Cluster_info"] = labels
                ppi_data.loc[:, "Center_X"] = centers[:,0]
                ppi_data.loc[:, "Center_Y"] = centers[:,1]
                ppi_data.loc[:, "Center_Z"] = centers[:,2] 
                
                self._create_chimera_session(ppi_data, reference_output_name, tmp_df)
            else:
                logger.error(f"Shape mismatch for {binder}: labels({len(labels)}) != data({len(ppi_data)}). Skipping.")
        
        # 6. Save Final Summary
        binder_df.to_csv(f"{self.output_path}/peptide_binder_info.csv", index=False)

    def _create_chimera_session(self,
                                ppi_data: pd.DataFrame, 
                                ref_model: str,
                                cluster_info: pd.DataFrame):
        """
        Generates and executes a ChimeraX script (.cxc) to visualize the analysis.

        This method writes a set of ChimeraX commands to:
        1. Load the reference binder structure.
        2. Color the binder's interface residues according to the cluster they interact with.
        3. Load and align all peptide structures, colored by their cluster ID.
        4. Represent cluster centroids as spheres.
        5. Save the session as a .cxs file for easy reopening.

        Parameters
        ----------
        ppi_data : pd.DataFrame
            DataFrame containing details of the peptide models (paths, cluster IDs, etc.).
        ref_model : str
            Path to the reference PDB file of the binder.
        cluster_info : pd.DataFrame
            Summary DataFrame containing cluster labels, centroids, and interacting residues.
        """
        import subprocess

        binder = ppi_data.Binder_name.values[0]

        # Use Pathlib for robust path handling
        base_dir = self.output_path / "prot_peptide" / binder
        script_path = base_dir / f"{binder}_peptide_binding.cxc"
        session_path = base_dir / f"{binder}_peptide_binding.cxs" 
        
        available_colors = ["cyan", "yellow", "magenta", "orange", "cornflower blue"]
        available_colors_ref = ["light coral", "medium slate blue", "orange", "green", "red", "yellow"]
        
        with open(script_path, "w") as f:
            ## Global settings
            f.write("graphics silhouettes true\n") 
            f.write("lighting soft\n") 
            f.write("set bg white\n") 

            ## Load reference   
            f.write(f"\n# --- {binder} REFERENCE ---\n")
            f.write(f"open \"{ref_model}\"\n")
            f.write(f"rename #1 {binder}_ref\n")

            ## Color ref residues based on cluster interactions
            for idx, cluster_data in cluster_info.iterrows():
                cluster_id = int(cluster_data["Cluster_label"])
                if cluster_id == -1:
                    continue # Skip noise
                
                # Join residues for selection
                tmp_sel_str = ",".join(map(str, cluster_data["Residues"]))
                
                color_index = cluster_id % len(available_colors_ref)
                color_str = available_colors_ref[color_index]
                
                f.write(f"color #1:{tmp_sel_str} {color_str}\n") 

                ## Draw centroid sphere for the cluster
                super_id = f"#5.{cluster_id + 1}"
                global_center_str = f"{cluster_data['Center_X']},{cluster_data['Center_Y']},{cluster_data['Center_Z']}"
                f.write(f"shape sphere name Centroid_{cluster_id+1}_Mean radius 3 center {global_center_str} color {color_str} model {super_id} \n")
             
            ## Load peptide_proteins and rename
            ppi_data["aligned_path"] = ppi_data["filtered_path"].str.replace("filtered", "aligned")

            for tmp_cluster in ppi_data["Cluster_info"].unique():
                tmp_cluster = int(tmp_cluster)
                current_sub_id = tmp_cluster + 2
                
                if tmp_cluster == -1:
                    color_str = "silver"
                    group_name = "Unclassified"
                
                else:
                    color_idx = tmp_cluster % len(available_colors) 
                    color_str = available_colors[color_idx]
                    group_name = f"Cluster_{tmp_cluster + 1}"

                models_in_cluster = ppi_data.loc[ppi_data["Cluster_info"] == tmp_cluster, :]
                
                for i, (idx, row) in enumerate(models_in_cluster.iterrows()):
                    # Model ID hierarchy: #3.ClusterID.ModelIndex
                    pep_id = f"#3.{current_sub_id}.{i + 1}" 
                    cen_id = f"#4.{current_sub_id}.{i + 1}" 
                    
                    # Open peptide 
                    f.write(f"open \"{row['aligned_path']}\" id {pep_id}\n")
                    
                    if tmp_cluster == -1:
                        model_name = f"{row['PPI']}_unclassified"    
                    else:
                        model_name = f"{row['PPI']}_c{current_sub_id}"
                    
                    f.write(f"rename {pep_id} {model_name}\n")
                    f.write(f"color {pep_id} {color_str}\n")

                    centroid_str = f"{row['Center_X']},{row['Center_Y']},{row['Center_Z']}"
                    f.write(f"shape sphere name {model_name} radius 1 center {centroid_str} color {color_str} model {cen_id}\n")
                f.write(f"rename #3.{current_sub_id} {group_name}\n")
                f.write(f"rename #4.{current_sub_id} {group_name}_Center_of_mass\n")   

            
            ## Final cleanup and save
            f.write(f"lighting depthCue false\n")
            f.write(f"rename #3 Peptides\n")
            f.write(f"hide #3/A cartoon\n") # Hide the Binder chain in the aligned peptide models
            f.write(f"hide atoms\n")
            f.write(f"rename #4 Peptide_centers\n")
            f.write(f"save {session_path}\n")
            f.write(f"exit\n")

        logger.info(f"Executing ChimeraX script: {script_path}")
        try:
            subprocess.run(["chimerax", "--nogui", str(script_path)], check=True)
        except FileNotFoundError:
            logger.error("ChimeraX executable not found in PATH. Script generated but not executed.")
        except subprocess.CalledProcessError as e:
            logger.error(f"ChimeraX execution failed: {e}")

    def cluster_protein_peptides(self, aligned_models: List[str], 
                                 reference_model: Union[str, Molecule], 
                                 **kwargs)-> tuple[pd.DataFrame, dict]:
        """
        Clusters peptide structures based on their spatial position relative to the binder.

        This method uses the DBSCAN algorithm to group peptides that bind to similar 
        regions on the reference protein surface. It calculates the centroid (Center of Mass) 
        of the peptide backbones (Chain B, CA atoms) and clusters these points.

        Parameters
        ----------
        aligned_models : List[str]
            List of file paths to the aligned PDB models.
        reference_model : str or Molecule
            The reference binder structure used to map the binding sites.
        **kwargs
            Arguments passed to the DBSCAN constructor (e.g., `eps=5`, `min_samples=3`).

        Returns
        -------
        pd.DataFrame
            Summary table with columns:
            - 'Cluster_label': The ID assigned by DBSCAN (-1 indicates noise).
            - 'Center_X/Y/Z': Geometric center of the cluster.
            - 'Residues': List of binder residues within 8Å of the cluster center.
        dict
            Dictionary containing raw 'cluster_labels' and 'peptide_centers' arrays.
        """
        
        # 1. Load Molecules
        mols = [Molecule(str(i)) for i in aligned_models]

        # 2. Resolve Reference
        if isinstance(reference_model, str):
            ref_mol = Molecule(reference_model)
        elif isinstance(reference_model, Molecule):
            ref_mol = reference_model
        else:
            raise ValueError("reference_model must be a path (str) or Molecule object")
        
        # 3. Get Reference Geometry
        xyz = ref_mol.get("coords", sel="protein")
        ref_resids = ref_mol.get("resid", sel="protein")
        
        # 4. Calculate Peptide Centroids (Chain B, Alpha Carbons)
        
        valid_centroids = []
        valid_indices = []
        for i, tmp_mol in enumerate(mols):
            coords = tmp_mol.get("coords", sel="chain B and name CA")
            if coords.size > 0:
                valid_centroids.append(coords.mean(axis=0))
                valid_indices.append(i)
            else:
                logger.warning(f"Model {aligned_models[i]} has no Chain B CA atoms. Skipping from clustering.")

        if not valid_centroids:
            return pd.DataFrame(), {"cluster_labels": np.array([]), "peptide_centers": np.array([])}

        mols_centroids = np.array(valid_centroids)

        # 5. Perform Clustering (DBSCAN)
        # kwargs allows passing eps, min_samples, etc.
        clustering = DBSCAN(**kwargs).fit(mols_centroids)
        
        # Adjust cluster labels for original input list
        full_labels = np.full(len(mols), -1, dtype=int)
        for idx, label in zip(valid_indices, clustering.labels_):
            full_labels[idx] = label

        # 6. Analyze Clusters
        cluster_labels = []
        cluster_centers = []
        all_nearby_residues = []

        unique_labels = np.unique(clustering.labels_)

        for cluster_label in unique_labels:
            cluster_labels.append(cluster_label)

            # Calculate geometric center of the cluster (mean of peptide centroids)
            mask = clustering.labels_ == cluster_label
            cluster_center = mols_centroids[mask].mean(axis=0)
            cluster_centers.append(cluster_center)

            # 7. Identify Binding Site Residues
            # Calculate distance from every protein atom to the cluster center
            tmp_centroid_distance = xyz - cluster_center
        
            # Euclidean norm (distance)
            tmp_euc = np.linalg.norm(tmp_centroid_distance, axis = 1)
            
            nearby_residues = np.unique(ref_resids[tmp_euc < 8])
            all_nearby_residues.append(nearby_residues)
        
        # 8. Format Output
        cluster_centers = np.array(cluster_centers)
        
        results_df = pd.DataFrame({
            "Cluster_label": cluster_labels,
            "Center_X": cluster_centers[:, 0],
            "Center_Y": cluster_centers[:, 1],
            "Center_Z": cluster_centers[:, 2],
            "Residues": all_nearby_residues
        })

        extra_info = {
            "cluster_labels": full_labels, 
            "peptide_centers": np.array([valid_centroids[valid_indices.index(i)] if i in valid_indices else [0,0,0] for i in range(len(mols))])
        }

        return results_df, extra_info

    # =========================================================================
    # --- Generic Analysis Methods ---
    # =========================================================================

    def _resolve_metric_col(self, preferred: str, fallback: str) -> Optional[str]:
        """Returns preferred column name if present, fallback if not, else None."""
        if self._interactome_data is None:
            return None
        if preferred in self._interactome_data.columns:
            return preferred
        if fallback in self._interactome_data.columns:
            return fallback
        return None

    def filter_by_metrics(self, criteria: Dict[str, Tuple[float, float]]) -> pd.DataFrame:
        """
        Filters the interactome by multiple metric ranges simultaneously.

        Parameters
        ----------
        criteria : Dict[str, Tuple[float, float]]
            Keys are column names, values are (min, max) inclusive ranges.
            Example: {"ipSAE_AB": (0.5, 1.0), "msa_depth": (20, 9999)}

        Returns
        -------
        pd.DataFrame
            Filtered subset of the interactome data.

        Raises
        ------
        RuntimeError
            If interactome data is not loaded.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()
        missing = [col for col in criteria if col not in df.columns]
        if missing:
            logger.warning(f"filter_by_metrics: columns not found and will be skipped: {missing}")

        mask = pd.Series(True, index=df.index)
        for col, (lo, hi) in criteria.items():
            if col in df.columns:
                mask &= df[col].between(lo, hi)

        result = df[mask].reset_index(drop=True)
        logger.info(f"filter_by_metrics: {len(result)}/{len(df)} rows passed the filter.")
        return result

    def get_top_interactions(
        self,
        metric: str = "ipSAE_AB",
        top_n: int = 10,
        ascending: bool = False,
    ) -> pd.DataFrame:
        """
        Returns the top N interactions ranked by a given metric.

        Falls back to 'ipSAE' if the preferred column is absent.

        Parameters
        ----------
        metric : str
            Column name to rank by. Defaults to "ipSAE_AB".
        top_n : int
            Number of interactions to return.
        ascending : bool
            If True, returns the N lowest values instead.

        Returns
        -------
        pd.DataFrame
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data
        fallback = metric.replace("_AB", "") if "_AB" in metric else metric
        col = metric if metric in df.columns else (fallback if fallback in df.columns else None)

        if col is None:
            raise ValueError(f"Column '{metric}' (and fallback '{fallback}') not found in interactome data.")

        return (
            df.sort_values(col, ascending=ascending)
            .head(top_n)
            .reset_index(drop=True)
        )

    def summarize_by_protein(self, ppi_separator: str = "__") -> pd.DataFrame:
        """
        Generates a per-protein summary across all interactions.

        Parses the 'PPI' column to extract individual protein IDs, then aggregates:
        - degree: number of interaction partners
        - mean_ipSAE, mean_pDockQ2: average confidence metrics
        - best_partner: partner with the highest ipSAE value

        Parameters
        ----------
        ppi_separator : str
            Delimiter used in the PPI column to separate the two protein IDs.
            Defaults to "__".

        Returns
        -------
        pd.DataFrame
            One row per protein with aggregated statistics.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()
        ipsae_col = self._resolve_metric_col("ipSAE_AB", "ipSAE")
        pdockq2_col = self._resolve_metric_col("pDockQ2_AB", "pDockQ2")

        try:
            split = df["PPI"].str.split(ppi_separator, n=1, expand=True)
            df["_prot_a"] = split[0]
            df["_prot_b"] = split[1] if 1 in split.columns else split[0]
        except Exception as e:
            raise ValueError(f"Failed to parse PPI column with separator '{ppi_separator}': {e}")

        records: Dict[str, Any] = {}

        for _, row in df.iterrows():
            for prot, partner in [(row["_prot_a"], row["_prot_b"]), (row["_prot_b"], row["_prot_a"])]:
                if prot not in records:
                    records[prot] = {"ipsae_vals": [], "pdockq2_vals": [], "partners": {}}
                ipsae_val = row[ipsae_col] if ipsae_col else np.nan
                records[prot]["ipsae_vals"].append(ipsae_val)
                if pdockq2_col:
                    records[prot]["pdockq2_vals"].append(row[pdockq2_col])
                # Track best partner by ipSAE
                current_best = records[prot]["partners"].get(partner, -np.inf)
                records[prot]["partners"][partner] = max(current_best, ipsae_val if not np.isnan(ipsae_val) else -np.inf)

        summary_rows = []
        for prot, data in records.items():
            ipsae_arr = [v for v in data["ipsae_vals"] if not np.isnan(v)]
            pdockq2_arr = [v for v in data["pdockq2_vals"] if not np.isnan(v)]
            best_partner = max(data["partners"], key=data["partners"].get) if data["partners"] else None
            summary_rows.append({
                "protein": prot,
                "degree": len(data["partners"]),
                "mean_ipSAE": np.mean(ipsae_arr) if ipsae_arr else np.nan,
                "max_ipSAE": np.max(ipsae_arr) if ipsae_arr else np.nan,
                "mean_pDockQ2": np.mean(pdockq2_arr) if pdockq2_arr else np.nan,
                "best_partner": best_partner,
            })

        result = pd.DataFrame(summary_rows).sort_values("degree", ascending=False).reset_index(drop=True)
        logger.info(f"summarize_by_protein: {len(result)} unique proteins found.")
        return result

    def export_to_network(
        self,
        output_format: str = "cytoscape",
        ppi_separator: str = "__",
        extra_cols: Optional[List[str]] = None,
    ) -> pd.DataFrame:
        """
        Exports the interactome as an edge list for network visualization tools.

        Produces a DataFrame compatible with Cytoscape (edge list format) or Gephi
        (with 'Source'/'Target' headers). Edge attributes include ipSAE, pDockQ2,
        pLDDT_mean, msa_depth, and Tier if present.

        Parameters
        ----------
        output_format : str
            "cytoscape" or "gephi". Controls header naming convention.
        ppi_separator : str
            Delimiter to split the PPI column into source/target nodes.
        extra_cols : list of str, optional
            Additional interactome columns to include as edge attributes.

        Returns
        -------
        pd.DataFrame
            Edge list with node and attribute columns.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()

        try:
            split = df["PPI"].str.split(ppi_separator, n=1, expand=True)
            df["_source"] = split[0]
            df["_target"] = split[1] if 1 in split.columns else split[0]
        except Exception as e:
            raise ValueError(f"Failed to parse PPI column with separator '{ppi_separator}': {e}")

        src_col, tgt_col = ("Source", "Target") if output_format == "gephi" else ("source", "target")

        default_attrs = ["ipSAE_AB", "ipSAE", "pDockQ2_AB", "pDockQ2",
                         "pLDDT_mean", "msa_depth", "Tier"]
        attr_cols = [c for c in default_attrs if c in df.columns]
        if extra_cols:
            attr_cols += [c for c in extra_cols if c in df.columns and c not in attr_cols]

        edge_df = df[["_source", "_target"] + attr_cols].rename(
            columns={"_source": src_col, "_target": tgt_col}
        ).reset_index(drop=True)

        logger.info(f"export_to_network: exported {len(edge_df)} edges with {len(attr_cols)} attributes.")
        return edge_df

    def compare_engines(
        self,
        other_df: pd.DataFrame,
        suffix_self: str = "_a",
        suffix_other: str = "_b",
        on: str = "PPI",
    ) -> pd.DataFrame:
        """
        Compares metrics between two interactome runs (e.g., AF3 vs Boltz2).

        Merges the loaded interactome with a second DataFrame on the PPI key,
        computing the delta for each shared numeric metric.

        Parameters
        ----------
        other_df : pd.DataFrame
            Second interactome result DataFrame. Must contain a 'PPI' column.
        suffix_self : str
            Suffix appended to columns from the loaded (self) interactome.
        suffix_other : str
            Suffix appended to columns from `other_df`.
        on : str
            Join key column name. Defaults to "PPI".

        Returns
        -------
        pd.DataFrame
            Merged DataFrame with per-metric delta columns (prefix 'delta_').
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")
        if on not in other_df.columns:
            raise ValueError(f"Column '{on}' not found in other_df.")

        merged = pd.merge(
            self._interactome_data,
            other_df,
            on=on,
            suffixes=(suffix_self, suffix_other),
            how="inner",
        )

        # Compute deltas for numeric columns that appear in both
        base_cols = set(self._interactome_data.columns) - {on}
        other_cols = set(other_df.columns) - {on}
        shared_numeric = [
            c for c in base_cols & other_cols
            if pd.api.types.is_numeric_dtype(self._interactome_data[c])
        ]

        for col in shared_numeric:
            try:
                merged[f"delta_{col}"] = merged[f"{col}{suffix_self}"] - merged[f"{col}{suffix_other}"]
            except KeyError:
                pass  # column may have been renamed or absent after merge

        logger.info(
            f"compare_engines: {len(merged)} PPIs in common, "
            f"{len(shared_numeric)} numeric metrics compared."
        )
        return merged

    def cluster_interactome_by_metrics(
        self,
        n_clusters: int = 4,
        metric_cols: Optional[List[str]] = None,
        random_state: int = 42,
    ) -> pd.DataFrame:
        """
        Applies K-Means clustering to group interactions by their metric profile.

        Discovers non-obvious interaction patterns beyond single-threshold filtering.
        Uses StandardScaler normalization before clustering to handle metric heterogeneity.

        Parameters
        ----------
        n_clusters : int
            Number of K-Means clusters. Defaults to 4.
        metric_cols : list of str, optional
            Columns to use as feature vector. If None, auto-selects all available
            numeric columns among: ipSAE_AB, pDockQ2_AB, pLDDT_mean, msa_depth,
            ipTM, pTM, and their non-suffixed variants.
        random_state : int
            Random seed for reproducibility.

        Returns
        -------
        pd.DataFrame
            Interactome data with an added 'km_cluster' column.
        """
        try:
            from sklearn.cluster import KMeans
            from sklearn.preprocessing import StandardScaler
        except ImportError:
            raise ImportError("scikit-learn is required for cluster_interactome_by_metrics.")

        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        df = self._interactome_data.copy()

        if metric_cols is None:
            candidates = [
                "ipSAE_AB", "ipSAE", "pDockQ2_AB", "pDockQ2",
                "pLDDT_mean", "msa_depth", "ipTM", "pTM",
                "ipSAE_d0_dom_AB", "ipSAE_d0dom_AB",
            ]
            metric_cols = [c for c in candidates if c in df.columns]
        else:
            metric_cols = [c for c in metric_cols if c in df.columns]

        if not metric_cols:
            raise ValueError("No valid metric columns found for clustering.")

        feature_matrix = df[metric_cols].copy()
        # Drop rows with all-NaN features; impute remaining NaNs with column median
        feature_matrix = feature_matrix.dropna(how="all")
        feature_matrix = feature_matrix.fillna(feature_matrix.median(numeric_only=True))

        if len(feature_matrix) < n_clusters:
            raise ValueError(
                f"Not enough valid rows ({len(feature_matrix)}) for {n_clusters} clusters."
            )

        scaler = StandardScaler()
        X = scaler.fit_transform(feature_matrix)

        kmeans = KMeans(n_clusters=n_clusters, random_state=random_state, n_init="auto")
        labels = kmeans.fit_predict(X)

        result = df.loc[feature_matrix.index].copy()
        result["km_cluster"] = labels

        logger.info(
            f"cluster_interactome_by_metrics: {n_clusters} clusters on {len(feature_matrix)} rows "
            f"using features {metric_cols}."
        )
        logger.info(f"Cluster sizes:\n{pd.Series(labels).value_counts().sort_index()}")
        return result.reset_index(drop=True)

    # -------------------------------------------------------------------------
    # Network topology analysis
    # -------------------------------------------------------------------------

    # Non-numeric columns excluded from rank aggregation
    _META_COLS: frozenset = frozenset({
        "PPI", "ORF_A", "ORF_B", "Folder", "Path",
        "LIR_AB", "cLIR_AB", "pool_id", "Tier", "LIS_Tier", "iLIS_Tier",
    })

    def _aggregate_per_ppi(
        self,
        model_agg: str = "mean",
        weight_col: Optional[str] = None,
    ) -> pd.DataFrame:
        """Collapse multiple model-rank rows into one row per PPI.

        Parameters
        ----------
        model_agg : str
            ``"mean"`` — average all numeric columns across ranks.
            ``"max"``  — take the per-column maximum across ranks.
            ``"best"`` — keep the single rank row with the highest ``weight_col``.
        weight_col : str, optional
            Required only for ``model_agg="best"``. The column used to pick the
            best rank.

        Returns
        -------
        pd.DataFrame
            One row per unique PPI with string meta columns preserved and
            numeric columns aggregated.

        Raises
        ------
        ValueError
            If ``model_agg`` is invalid, or ``weight_col`` is missing when
            ``model_agg="best"``.
        """
        df = self._interactome_data.copy()

        if model_agg not in ("mean", "max", "best"):
            raise ValueError(f"model_agg must be 'mean', 'max', or 'best'. Got: '{model_agg}'")
        if model_agg == "best" and (weight_col is None or weight_col not in df.columns):
            raise ValueError(
                f"model_agg='best' requires a valid weight_col. Got: '{weight_col}'"
            )

        num_cols = [
            c for c in df.columns
            if c not in self._META_COLS and pd.api.types.is_numeric_dtype(df[c])
        ]
        meta_present = [c for c in df.columns if c != "PPI" and c not in num_cols]

        if model_agg == "best":
            return df.loc[df.groupby("PPI")[weight_col].idxmax()].reset_index(drop=True)

        meta = df.groupby("PPI")[meta_present].first().reset_index() if meta_present \
            else df.groupby("PPI")[[]].first().reset_index()
        agg_fn = df.groupby("PPI")[num_cols].mean() if model_agg == "mean" \
            else df.groupby("PPI")[num_cols].max()
        return meta.merge(agg_fn.reset_index(), on="PPI")

    def _build_ppi_graph(
        self,
        weight_col: str,
        min_weight: float,
        ppi_separator: str,
        model_agg: str,
    ) -> Any:
        """Build a weighted undirected NetworkX graph from _interactome_data."""
        try:
            import networkx as nx
        except ImportError:
            raise ImportError("networkx is required. Install with: pip install networkx")

        if weight_col not in self._interactome_data.columns:
            raise ValueError(f"Column '{weight_col}' not found in interactome data.")

        ppi_df = self._aggregate_per_ppi(model_agg=model_agg, weight_col=weight_col)

        G = nx.Graph()
        for _, row in ppi_df.iterrows():
            parts = str(row["PPI"]).split(ppi_separator, 1)
            if len(parts) != 2:
                logger.warning(f"Cannot parse PPI '{row['PPI']}' with separator '{ppi_separator}'. Skipping.")
                continue
            source, target = parts
            w = float(row[weight_col]) if not pd.isna(row[weight_col]) else 0.0
            if w > min_weight:
                G.add_edge(source, target, weight=w)

        return G

    def compute_network_properties(
        self,
        weight_col: str = "Best_iLIS",
        min_weight: float = 0.0,
        ppi_separator: str = "__",
        model_agg: str = "mean",
    ) -> pd.DataFrame:
        """Compute graph-theory metrics for every protein in the interactome.

        Aggregates multiple model-rank rows per PPI using ``model_agg``, builds a
        weighted undirected NetworkX graph, and returns per-protein centrality metrics.
        Hubs and bottlenecks are identified using adaptive thresholds (mean + 1σ of
        degree and betweenness distributions respectively), making the classification
        valid for any proteome size.

        Parameters
        ----------
        weight_col : str
            Numeric column to use as edge weight. Defaults to ``"Best_iLIS"``.
        min_weight : float
            Edges with weight ≤ min_weight are excluded. Defaults to ``0.0``
            (keeps all pairs with any detectable interaction signal).
        ppi_separator : str
            Separator used in the PPI column. Defaults to ``"__"``.
        model_agg : str
            Strategy to collapse multiple model-rank rows per PPI:
            ``"mean"`` (average across ranks), ``"max"`` (take maximum),
            or ``"best"`` (keep the rank with the highest weight_col value).
            Defaults to ``"mean"``.

        Returns
        -------
        pd.DataFrame
            One row per protein with columns: ``protein``, ``degree``,
            ``weighted_degree``, ``betweenness_centrality``,
            ``closeness_centrality``, ``eigenvector_centrality``,
            ``clustering_coefficient``, ``is_hub``, ``is_bottleneck``.
            Sorted descending by ``degree``.

        Raises
        ------
        RuntimeError
            If interactome data is not loaded.
        ValueError
            If ``weight_col`` is absent or ``model_agg`` is invalid.
        ImportError
            If ``networkx`` is not installed.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        G = self._build_ppi_graph(weight_col, min_weight, ppi_separator, model_agg)

        if G.number_of_nodes() == 0:
            logger.warning("compute_network_properties: graph has no nodes after filtering.")
            return pd.DataFrame(columns=[
                "protein", "degree", "weighted_degree",
                "betweenness_centrality", "closeness_centrality",
                "eigenvector_centrality", "clustering_coefficient",
                "is_hub", "is_bottleneck",
            ])

        import networkx as nx

        degrees = dict(G.degree())
        weighted_degrees = dict(G.degree(weight="weight"))
        betweenness = nx.betweenness_centrality(G, weight="weight", normalized=True)
        closeness = nx.closeness_centrality(G)

        try:
            eigenvector = nx.eigenvector_centrality(G, weight="weight", max_iter=1000)
        except nx.PowerIterationFailedConvergence:
            logger.warning("Eigenvector centrality failed to converge; values set to NaN.")
            eigenvector = {n: np.nan for n in G.nodes()}

        clustering = nx.clustering(G, weight="weight")

        deg_vals = np.array(list(degrees.values()), dtype=float)
        bet_vals = np.array(list(betweenness.values()), dtype=float)
        hub_threshold = float(deg_vals.mean() + deg_vals.std())
        bottleneck_threshold = float(bet_vals.mean() + bet_vals.std())

        rows = [
            {
                "protein": node,
                "degree": degrees[node],
                "weighted_degree": round(weighted_degrees[node], 4),
                "betweenness_centrality": round(betweenness[node], 4),
                "closeness_centrality": round(closeness[node], 4),
                "eigenvector_centrality": round(eigenvector[node], 4)
                    if not np.isnan(eigenvector[node]) else np.nan,
                "clustering_coefficient": round(clustering[node], 4),
                "is_hub": bool(degrees[node] > hub_threshold),
                "is_bottleneck": bool(betweenness[node] > bottleneck_threshold),
            }
            for node in G.nodes()
        ]

        result = (
            pd.DataFrame(rows)
            .sort_values("degree", ascending=False)
            .reset_index(drop=True)
        )
        logger.info(
            f"compute_network_properties: {G.number_of_nodes()} nodes, "
            f"{G.number_of_edges()} edges. "
            f"Hubs: {result['is_hub'].sum()}, Bottlenecks: {result['is_bottleneck'].sum()}."
        )
        return result

    def plot_network(
        self,
        network_df: Optional[pd.DataFrame] = None,
        color_by: str = "betweenness_centrality",
        size_by: str = "degree",
        weight_col: str = "Best_iLIS",
        min_weight: float = 0.0,
        ppi_separator: str = "__",
        model_agg: str = "mean",
        label_top_n: int = 5,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "Interactome Network",
    ) -> None:
        """Visualise the PPI network using a force-directed spring layout.

        Node size encodes ``size_by``, node colour encodes ``color_by`` (viridis
        colormap). Edge width scales with interaction weight. Only the top
        ``label_top_n`` nodes by ``size_by`` are labelled to avoid clutter.
        Hub and bottleneck nodes are outlined in red and blue respectively.

        Parameters
        ----------
        network_df : pd.DataFrame, optional
            Pre-computed output of :meth:`compute_network_properties`. If ``None``,
            it is computed using ``weight_col``, ``min_weight``, ``ppi_separator``,
            and ``model_agg``.
        color_by : str
            Node attribute column for colour mapping. Defaults to
            ``"betweenness_centrality"``.
        size_by : str
            Node attribute column for size scaling. Defaults to ``"degree"``.
        weight_col : str
            Edge weight column (used when rebuilding the graph). Defaults to
            ``"Best_iLIS"``.
        min_weight : float
            Edge weight threshold (used when rebuilding the graph).
        ppi_separator : str
            PPI column separator.
        model_agg : str
            Model-rank aggregation strategy.
        label_top_n : int
            Number of highest-``size_by`` nodes to label. Defaults to ``5``.
        output_path : str or Path, optional
            If provided, saves the figure to this path (300 dpi). Otherwise
            calls ``plt.show()``.
        title : str
            Figure title.

        Raises
        ------
        RuntimeError
            If interactome data is not loaded.
        ImportError
            If ``networkx`` or ``matplotlib`` is not installed.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        if network_df is None:
            network_df = self.compute_network_properties(
                weight_col=weight_col,
                min_weight=min_weight,
                ppi_separator=ppi_separator,
                model_agg=model_agg,
            )

        G = self._build_ppi_graph(weight_col, min_weight, ppi_separator, model_agg)
        _plot_network_figure(
            G, network_df,
            color_by=color_by, size_by=size_by,
            label_top_n=label_top_n, output_path=output_path, title=title,
        )

    # -------------------------------------------------------------------------
    # Database cross-validation
    # -------------------------------------------------------------------------

    def validate_against_database(
        self,
        known_ppis: DatabaseClient,
        id_map: Optional[Dict[str, str]] = None,
        ppi_separator: str = "__",
        model_agg: str = "mean",
    ) -> pd.DataFrame:
        """Cross-validate predicted PPIs against a reference PPI database.

        Parameters
        ----------
        known_ppis:
            Reference database built with :meth:`DatabaseClient.from_file`.
        id_map:
            Maps interactome protein IDs to database IDs.
            E.g. ``{"ORF1": "gene1"}``.  IDs absent from the map are treated
            as unmappable and yield ``experimental_support = NaN``.
            If ``None``, IDs are assumed to match the database directly.
        ppi_separator:
            Separator used in the ``PPI`` column. Default ``"__"``.
        model_agg:
            Aggregation strategy passed to :meth:`_aggregate_per_ppi`
            (``"mean"``, ``"max"``, or ``"best"``).

        Returns
        -------
        pd.DataFrame
            One row per unique PPI with all numeric metrics aggregated and an
            ``experimental_support`` column:

            - ``True``  — pair found in the reference database.
            - ``False`` — both proteins are in the database but the pair is
                          not recorded.
            - ``NaN``   — at least one protein is absent from the database
                          (interaction is not assessable).

        Raises
        ------
        RuntimeError
            If interactome data is not loaded.
        """
        if self._interactome_data is None:
            raise RuntimeError("Interactome data not loaded. Set interactome_path first.")

        ppi_df = self._aggregate_per_ppi(model_agg=model_agg)
        db_proteins = known_ppis.proteins

        def _support(ppi_str: str) -> Optional[bool]:
            parts = ppi_str.split(ppi_separator, 1)
            if len(parts) != 2:
                return None
            id_a, id_b = parts
            if id_map is not None:
                id_a = id_map.get(id_a)
                id_b = id_map.get(id_b)
                if id_a is None or id_b is None:
                    return None
            if id_a not in db_proteins or id_b not in db_proteins:
                return None
            return (id_a, id_b) in known_ppis

        ppi_df["experimental_support"] = ppi_df["PPI"].map(_support)
        return ppi_df

    def validation_summary(
        self,
        validated_df: pd.DataFrame,
        group_by: str = "Tier",
        known_ppis: Optional[DatabaseClient] = None,
        ppi_separator: str = "__",
    ) -> pd.DataFrame:
        """Summarise cross-validation results as precision / recall / F1 per group.

        Parameters
        ----------
        validated_df:
            Output of :meth:`validate_against_database` — one row per PPI with
            an ``experimental_support`` column.
        group_by:
            Column in ``validated_df`` to group by (e.g. ``"Tier"``,
            ``"iLIS_Tier"``). Defaults to ``"Tier"``.
        known_ppis:
            The same :class:`DatabaseClient` used in
            :meth:`validate_against_database`. When provided, enables recall
            and F1 computation. Recall denominator = experimental PPIs where
            both proteins appear anywhere in the interactome data
            (reachable subset).
        ppi_separator:
            Separator in the ``PPI`` column. Default ``"__"``.

        Returns
        -------
        pd.DataFrame
            One row per group plus an ``"Overall"`` row. Columns:

            - ``<group_by>`` — group label.
            - ``n_predicted`` — total PPIs in the group.
            - ``n_assessable`` — PPIs where ``experimental_support`` is not NaN.
            - ``n_supported`` — ``experimental_support == True`` (TP).
            - ``n_unconfirmed`` — ``experimental_support == False`` (not in database,
              but assessable — may be a true interaction not yet documented).
            - ``precision`` — n_supported / (n_supported + n_unconfirmed).
            - ``n_reachable_experimental`` *(if known_ppis provided)* — reachable
              experimental PPIs used as recall denominator (same for all rows).
            - ``recall`` *(if known_ppis provided)* — TP / n_reachable_experimental.
            - ``f1`` *(if known_ppis provided)* — harmonic mean of precision and recall.

        Raises
        ------
        ValueError
            If ``group_by`` or ``experimental_support`` columns are missing.
        """
        if "experimental_support" not in validated_df.columns:
            raise ValueError(
                "validated_df must contain 'experimental_support'. "
                "Call validate_against_database first."
            )
        if group_by not in validated_df.columns:
            raise ValueError(
                f"Column '{group_by}' not found in validated_df. "
                f"Available columns: {validated_df.columns.tolist()}"
            )

        def _metrics(sub: pd.DataFrame) -> dict:
            n_predicted = len(sub)
            n_assessable = int(sub["experimental_support"].notna().sum())
            n_supported = int((sub["experimental_support"] == True).sum())
            n_unconfirmed = int((sub["experimental_support"] == False).sum())
            precision = n_supported / n_assessable if n_assessable > 0 else float("nan")
            return {
                "n_predicted": n_predicted,
                "n_assessable": n_assessable,
                "n_supported": n_supported,
                "n_unconfirmed": n_unconfirmed,
                "precision": precision,
            }

        rows = []
        for group_val, sub in validated_df.groupby(group_by, sort=False):
            row = {group_by: group_val}
            row.update(_metrics(sub))
            rows.append(row)

        overall = {group_by: "Overall"}
        overall.update(_metrics(validated_df))
        rows.append(overall)

        summary = pd.DataFrame(rows).reset_index(drop=True)

        if known_ppis is not None:
            interactome_proteins: set = set()
            for ppi_str in validated_df["PPI"]:
                parts = ppi_str.split(ppi_separator, 1)
                if len(parts) == 2:
                    interactome_proteins.update(parts)

            n_reachable = sum(
                1 for pair in known_ppis.ppis
                if pair.issubset(interactome_proteins)
            )

            def _recall_f1(tp: int, prec: float) -> tuple:
                recall = tp / n_reachable if n_reachable > 0 else float("nan")
                denom = prec + recall
                f1 = (2 * prec * recall / denom) if (denom > 0 and not (
                    pd.isna(prec) or pd.isna(recall))) else float("nan")
                return recall, f1

            summary["n_reachable_experimental"] = n_reachable
            summary["recall"] = summary.apply(
                lambda r: _recall_f1(r["n_supported"], r["precision"])[0], axis=1
            )
            summary["f1"] = summary.apply(
                lambda r: _recall_f1(r["n_supported"], r["precision"])[1], axis=1
            )

        return summary

    # -------------------------------------------------------------------------
    # Foldseek structural homology search
    # -------------------------------------------------------------------------

    # _FOLDSEEK_API = "https://search.foldseek.com/api"

    # def _submit_foldseek_job(
    #     self,
    #     cif_content: str,
    #     databases: List[str],
    #     mode: str = "3diaa",
    # ) -> str:
    #     """
    #     Submits a structure search to the Foldseek web API.

    #     Parameters
    #     ----------
    #     cif_content : str
    #         Raw text content of the CIF file.
    #     databases : list of str
    #         Foldseek database identifiers (e.g. ``["afdb-swissprot", "pdb100"]``).
    #     mode : str, optional
    #         Search mode. ``"3diaa"`` (default) or ``"tmalign"``.

    #     Returns
    #     -------
    #     str
    #         Ticket ID assigned by the Foldseek server.

    #     Raises
    #     ------
    #     ImportError
    #         If ``requests`` is not installed.
    #     RuntimeError
    #         If the server returns a non-200 status code.
    #     """
    #     try:
    #         import requests
    #     except ImportError:
    #         raise ImportError("requests is required for Foldseek searches. Install it with: pip install requests")

    #     payload: Dict[str, Any] = {"q": cif_content, "mode": mode}
    #     for db in databases:
    #         payload.setdefault("database[]", [])
    #         payload["database[]"].append(db)  # type: ignore[union-attr]

    #     response = requests.post(f"{self._FOLDSEEK_API}/ticket", data=payload, timeout=30)
    #     if response.status_code != 200:
    #         raise RuntimeError(
    #             f"Foldseek submission failed (HTTP {response.status_code}): {response.text}"
    #         )
    #     ticket_id: str = response.json()["id"]
    #     return ticket_id

    # def _poll_foldseek_job(
    #     self,
    #     ticket_id: str,
    #     poll_interval: int = 10,
    #     timeout: int = 600,
    # ) -> None:
    #     """
    #     Polls the Foldseek API until the job completes or times out.

    #     Parameters
    #     ----------
    #     ticket_id : str
    #         Ticket ID returned by :meth:`_submit_foldseek_job`.
    #     poll_interval : int, optional
    #         Seconds between status checks. Defaults to 10.
    #     timeout : int, optional
    #         Maximum total wait time in seconds. Defaults to 600.

    #     Raises
    #     ------
    #     TimeoutError
    #         If the job does not complete within ``timeout`` seconds.
    #     RuntimeError
    #         If the server reports an ``ERROR`` status.
    #     """
    #     try:
    #         import requests
    #     except ImportError:
    #         raise ImportError("requests is required for Foldseek searches. Install it with: pip install requests")

    #     elapsed = 0
    #     while elapsed < timeout:
    #         resp = requests.get(f"{self._FOLDSEEK_API}/ticket/{ticket_id}", timeout=30)
    #         resp.raise_for_status()
    #         status = resp.json().get("status", "")
    #         if status == "COMPLETE":
    #             return
    #         if status == "ERROR":
    #             raise RuntimeError(f"Foldseek job {ticket_id} reported ERROR status.")
    #         time.sleep(poll_interval)
    #         elapsed += poll_interval

    #     raise TimeoutError(
    #         f"Foldseek job {ticket_id} did not complete within {timeout}s."
    #     )

    # def _download_foldseek_results(
    #     self,
    #     ticket_id: str,
    #     out_dir: Path,
    #     protein_id: str,
    # ) -> Path:
    #     """
    #     Downloads and decompresses Foldseek results for one protein.

    #     Parameters
    #     ----------
    #     ticket_id : str
    #         Completed ticket ID.
    #     out_dir : Path
    #         Directory where the raw TSV is written.
    #     protein_id : str
    #         Used as the output filename stem: ``{protein_id}.tsv``.

    #     Returns
    #     -------
    #     Path
    #         Path to the written TSV file.

    #     Raises
    #     ------
    #     RuntimeError
    #         If the download request fails.
    #     """
    #     try:
    #         import requests
    #     except ImportError:
    #         raise ImportError("requests is required for Foldseek searches. Install it with: pip install requests")

    #     import io
    #     import tarfile

    #     resp = requests.get(
    #         f"{self._FOLDSEEK_API}/result/download/{ticket_id}",
    #         timeout=120,
    #         stream=True,
    #     )
    #     if resp.status_code != 200:
    #         raise RuntimeError(
    #             f"Failed to download Foldseek results for {protein_id} "
    #             f"(HTTP {resp.status_code}): {resp.text}"
    #         )

    #     tsv_path = out_dir / f"{protein_id}.tsv"
    #     raw_bytes = resp.content

    #     # The API returns a tar.gz archive containing one or more TSV files
    #     try:
    #         with tarfile.open(fileobj=io.BytesIO(raw_bytes), mode="r:gz") as tar:
    #             tsv_lines: List[str] = []
    #             for member in tar.getmembers():
    #                 if member.name.endswith(".tsv") or member.name.endswith(".m8"):
    #                     f = tar.extractfile(member)
    #                     if f is not None:
    #                         tsv_lines.append(f.read().decode("utf-8"))
    #             content = "\n".join(tsv_lines)
    #     except tarfile.TarError:
    #         # Fallback: server returned plain TSV
    #         content = raw_bytes.decode("utf-8")

    #     tsv_path.write_text(content, encoding="utf-8")
    #     return tsv_path

    # def run_foldseek_search(
    #     self,
    #     protein_ids: List[str],
    #     monomer_cif_dir: Union[str, Path],
    #     databases: List[str] = ("afdb-swissprot", "pdb100"),  # type: ignore[assignment]
    #     top_n: int = 10,
    #     evalue_cutoff: float = 1e-3,
    #     output_dir: Optional[Union[str, Path]] = None,
    #     best_plddt: bool = False,
    #     poll_interval: int = 10,
    #     timeout: int = 600,
    #     mode: str = "3diaa",
    # ) -> pd.DataFrame:
    #     """
    #     Searches each protein's monomer structure against Foldseek databases.

    #     Operates standalone — does not require :attr:`interactome_data` to be loaded.
    #     For each protein in ``protein_ids`` the method locates the corresponding
    #     CIF file in ``monomer_cif_dir``, submits it to the Foldseek web API,
    #     polls until completion, downloads results, and aggregates a summary.

    #     The folder layout expected inside ``monomer_cif_dir`` mirrors the output of
    #     AF3/Boltz2/ColabFold in single-protein mode::

    #         monomer_cif_dir/
    #         ├── proteinA/
    #         │   ├── proteinA_model_0.cif
    #         │   └── proteinA_model_1.cif
    #         └── proteinB/
    #             └── proteinB_model_0.cif

    #     Parameters
    #     ----------
    #     protein_ids : list of str
    #         Protein identifiers to search. Each must have a matching subdirectory
    #         inside ``monomer_cif_dir``.
    #     monomer_cif_dir : str or Path
    #         Root directory containing one subdirectory per protein, each with
    #         ``*model*.cif`` files.
    #     databases : list of str, optional
    #         Foldseek databases to search. Defaults to
    #         ``["afdb-swissprot", "pdb100"]``.
    #         Other available options: ``"afdb50"``, ``"afdb-proteome"``,
    #         ``"mgnify_esm30"``, ``"gmgcl_id"``.
    #     top_n : int, optional
    #         Maximum number of hits to retain per protein in the summary.
    #         Defaults to 10.
    #     evalue_cutoff : float, optional
    #         Hits with e-value above this threshold are discarded. Defaults to 1e-3.
    #     output_dir : str or Path, optional
    #         Root output directory. Defaults to :attr:`output_path`.
    #         Raw TSVs are written to ``{output_dir}/foldseek_results/``.
    #         The summary CSV is written to ``{output_dir}/foldseek_summary.csv``.
    #     best_plddt : bool, optional
    #         If ``False`` (default), uses the model with the lowest index
    #         (``model_0`` first, by sorted filename). If ``True``, parses all
    #         available models and selects the one with the highest mean pLDDT —
    #         useful when multiple models per protein are present.
    #     poll_interval : int, optional
    #         Seconds between Foldseek status checks. Defaults to 10.
    #     timeout : int, optional
    #         Maximum seconds to wait for a single job. Defaults to 600.
    #     mode : str, optional
    #         Foldseek search mode. ``"3diaa"`` (default) or ``"tmalign"``.

    #     Returns
    #     -------
    #     pd.DataFrame
    #         Summary DataFrame with columns:
    #         ``protein_id``, ``rank``, ``target``, ``fident``, ``alnlen``,
    #         ``evalue``, ``bits``, ``qstart``, ``qend``, ``tstart``, ``tend``.
    #         Also written to ``{output_dir}/foldseek_summary.csv``.

    #     Raises
    #     ------
    #     FileNotFoundError
    #         If no CIF file is found for a given protein ID.
    #     RuntimeError
    #         If the Foldseek API returns an unexpected error.
    #     TimeoutError
    #         If a job exceeds ``timeout`` seconds.
    #     """
    #     databases = list(databases)
    #     base_dir = Path(output_dir) if output_dir is not None else self.output_path
    #     raw_dir = base_dir / "foldseek_results"
    #     raw_dir.mkdir(parents=True, exist_ok=True)
    #     summary_csv = base_dir / "foldseek_summary.csv"

    #     cif_root = Path(monomer_cif_dir)
    #     summary_rows: List[Dict[str, Any]] = []

    #     _RAW_COLS = [
    #         "query", "target", "fident", "alnlen", "mismatch",
    #         "gapopen", "qstart", "qend", "tstart", "tend", "evalue", "bits",
    #     ]

    #     for protein_id in protein_ids:
    #         protein_dir = cif_root / protein_id
    #         if not protein_dir.exists():
    #             logger.warning(f"No directory found for '{protein_id}' in {cif_root}. Skipping.")
    #             continue

    #         cif_candidates = sorted(protein_dir.glob("*model*.cif"))
    #         if not cif_candidates:
    #             logger.warning(f"No CIF files found for '{protein_id}'. Skipping.")
    #             continue

    #         # Select which model to submit
    #         if best_plddt and len(cif_candidates) > 1:
    #             best_cif: Optional[Path] = None
    #             best_score = -1.0
    #             for candidate in cif_candidates:
    #                 try:
    #                     # engine unknown here — try all parsers
    #                     for eng in ("af3", "boltz", "colabfold"):
    #                         try:
    #                             stats = InteractomeProcessor._extract_monomer_plddt(candidate, eng)
    #                             score = stats.get("plddt_mean", -1.0)
    #                             if not np.isnan(score) and score > best_score:
    #                                 best_score = score
    #                                 best_cif = candidate
    #                             break
    #                         except Exception:
    #                             continue
    #                 except Exception:
    #                     continue
    #             cif_path = best_cif if best_cif is not None else cif_candidates[0]
    #         else:
    #             cif_path = cif_candidates[0]

    #         logger.info(f"Submitting {protein_id} ({cif_path.name}) to Foldseek...")

    #         try:
    #             cif_content = cif_path.read_text(encoding="utf-8")
    #             ticket_id = self._submit_foldseek_job(cif_content, databases, mode=mode)
    #             self._poll_foldseek_job(ticket_id, poll_interval=poll_interval, timeout=timeout)
    #             tsv_path = self._download_foldseek_results(ticket_id, raw_dir, protein_id)
    #         except (RuntimeError, TimeoutError, OSError) as exc:
    #             logger.error(f"Foldseek search failed for '{protein_id}': {exc}")
    #             continue

    #         # Parse raw TSV
    #         try:
    #             df_raw = pd.read_csv(
    #                 tsv_path,
    #                 sep="\t",
    #                 header=None,
    #                 names=_RAW_COLS,
    #                 comment="#",
    #             )
    #         except Exception as exc:
    #             logger.warning(f"Could not parse TSV for '{protein_id}': {exc}")
    #             continue

    #         df_filtered = df_raw[df_raw["evalue"] <= evalue_cutoff].copy()
    #         df_top = df_filtered.sort_values("evalue").head(top_n).reset_index(drop=True)
    #         df_top.insert(0, "protein_id", protein_id)
    #         df_top.insert(1, "rank", range(1, len(df_top) + 1))

    #         keep_cols = [
    #             "protein_id", "rank", "target", "fident", "alnlen",
    #             "evalue", "bits", "qstart", "qend", "tstart", "tend",
    #         ]
    #         summary_rows.append(df_top[[c for c in keep_cols if c in df_top.columns]])
    #         logger.info(
    #             f"  {protein_id}: {len(df_top)} hits retained "
    #             f"(e-value ≤ {evalue_cutoff}, top {top_n})."
    #         )

    #     if summary_rows:
    #         summary_df = pd.concat(summary_rows, ignore_index=True)
    #     else:
    #         summary_df = pd.DataFrame(columns=[
    #             "protein_id", "rank", "target", "fident", "alnlen",
    #             "evalue", "bits", "qstart", "qend", "tstart", "tend",
    #         ])

    #     summary_df.to_csv(summary_csv, index=False)
    #     logger.info(f"Foldseek summary saved to {summary_csv}")
    #     return summary_df
