
from moleculekit.molecule import Molecule
from .utils import process_full_data_af3, process_full_data_af3 

class MoleculeModel(Molecule):

    VALID_MODEL_TYPES = {"AF3", "boltz"}

    def __init__(self, filename=None, model_type="AF3", pae=None, plddt_atom=None, ptm=None, iptm=None, chain_by_res=None):
        if model_type not in self.VALID_MODEL_TYPES:
            raise ValueError(f"model_type debe ser uno de {self.VALID_MODEL_TYPES}, no '{model_type}'")
        
        super().__init__(filename)
        self.model_type = model_type
        self.pae = pae
        self.plddt_atom = plddt_atom
        self.plddt_res = plddt_atom
        self.cbplddt = None
        self.ptm = ptm
        self.iptm = iptm
        self.chain_by_res = chain_by_res
        ## Check pae dimesions with number of residues

    @classmethod
    def from_af3(cls, filename, json_path):
        data = process_full_data_af3(json_path)
        return cls(filename, model_type="AF3", pae=data["pae"], 
                   plddt_atom=data["atom_plddt"], plddt_res=data["res_plddt"], 
                   ptm=data["ptm"], iptm=data["iptm"])
    
    @classmethod
    def from_boltz(cls, filename, json_path):
        data = process_full_data_af3(json_path)
        return cls(filename, model_type="boltz", pae=data["pae"], 
                   plddt_atom=data["atom_plddt"], plddt_res=data["res_plddt"])
    
    def plot_plddt(self):
        pass

    def plot_pae(self):
        pass

    def process_ppi(self)-> tuple[list, pd.DataFrame]:
        """
        Processes an AlphaFold3 CIF model file and extracts structural and confidence metrics.

        This function parses metadata from the CIF file path, loads associated JSON files containing
        summary confidences and full structural data, and computes various metrics such as pLDDT means,
        PAE means (overall and per chain), and clustering information from the PAE submatrix between chains.
        It also generates a cluster plot and returns both summary metrics and cluster details.

        Parameters
        ----------
        model_file : str
            Path to the CIF file generated by AlphaFold3 or Boltz2.

        Returns
        -------
        list
            A list containing summary metrics:
            [ppi_id, orf_a, orf_b, folder_path, model_number, fraction_disordered, iPTM, pTM,
            chain_length_A, chain_length_B, plddt_mean, plddt_mean_chain_A, plddt_mean_chain_B,
            mean_pae, mean_pae_chain_A, mean_pae_chain_B, mean_pae_chain_A_B]
        pd.DataFrame
            DataFrame containing cluster information extracted from the PAE submatrix.

        Raises
        ------
        FileNotFoundError
            If associated JSON files are missing.
        KeyError
            If expected keys are missing in the JSON data.
        ValueError
            If the CIF file path format is invalid or model number cannot be extracted.
        """
        print(self.fileloc)
        # Extract folder name and model number
        # ppi_id = model_file.split("/")[-2].replace(prefix, "") ## This should be general
        # model_number = int(model_file.split("/")[-1].split("_")[-1].replace(".cif", ""))
        # orf_a, orf_b = ppi_id.split("__")
        # folder_path = "/".join(model_file.split("/")[1:-1])
        # if model_type == "af3":
        #     # Name for summary confidences file
        #     summary_confidences_file = model_file.replace(".cif",".json").replace("model","summary_confidences")
        #     # Name for full data file 
        #     full_data_file = summary_confidences_file.replace("summary_confidences","full_data")
        #     # Open summary confidences file
        #     summary_data = load_json(summary_confidences_file)
            
        #     # with open (summary_confidences_file,"r") as sc:
        #     #     # Load json data
        #     #     summary_data = json.load(sc)
        #     #     # Extract fraction disordered, iPTM and pTM
        #     #     fraction_disordered = summary_data["fraction_disordered"]
        #     # Process full data file (json file)
        #     full_data = process_full_data_af3(full_data_file)
        # elif model_type == "boltz2":
        #     summary_file = model_file.replace(".cif", ".json").replace(f"{ppi_id}_model", f"confidence_{ppi_id}_model")
        #     summary_data = load_json(summary_file)
        #     full_data = process_full_data_boltz(os.path.dirname(model_file))
        
        # import pdb;pdb.set_trace()
        iPTM = summary_data["iptm"]
        pTM = summary_data["ptm"]

        mol = Molecule(model_file)
        all_metrics = calculate_all_metrics(mol, full_data)

        ## Here, we do cluster of PAE AB submatrix, we already have the submatrix
        chain_by_res = full_data["token_chain_ids"]
        pae = full_data["pae"]
        pae_submatrix_1 = pae[chain_by_res == "A"][:, chain_by_res == "B"]
        pae_submatrix_2 = pae[chain_by_res == "B"][:, chain_by_res == "A"].T
        submatrix = np.min([pae_submatrix_1, pae_submatrix_2], axis=0) ## Maybe we want the mean?

        ## Clustering
        low_coords, cluster_labels = cluster_pae(submatrix)

        ## here we do the plot of the pae clusters
        plot_pae_clusters(submatrix,low_coords, cluster_labels, save_name=model_file.replace(".cif", "_cluster.png")) 
        
        cluster_data = cluster_info(low_coords=low_coords, cluster_labels=cluster_labels)
        # Incluir en el df de los clusters el ppi_id
        # import pdb;pdb.set_trace()
        if len(cluster_data)>0:
            cluster_data.loc[:, "PPI"] = ppi_id 
            cluster_data.loc[:, "Model_num"] = model_number 

        return {"PPI": ppi_id, "ORF_A": orf_a, "ORF_B":orf_b, "Folder": folder_path, 
                "Model_num": model_number, 
                # "Fraction_disordered": fraction_disordered, 
                "iPTM": self.iptm, 
                "pTM": self.ptm, 
                # "chain_length_A": np.sum(chain_by_res == "A"), "chain_length_B":np.sum(chain_by_res == "B"), 
                **all_metrics
                }, cluster_data