
import matplotlib.pyplot as plt
from pathlib import Path
from matplotlib.patches import Rectangle
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from .utils import load_json, process_full_data_af3


def plot_paes (summary_confidences_path: str, fulldata_path: str, save_name: str = None):

    """
    Generate a PAE's graphic (Predicted Aligned Error) using AF3 results.

    ARGS IN:
    ----------
    summary_confidences : str
        Path to JSON's file with summary confidences (ptm, iptm, etc).
    jsonpath : str
        Path to JSON's file with PAE's matrix.
    save_name : str
        Name which will be used in order to save the file
    outdir : str, optional ## actualizar con save name
        Outpit directory where the image will be saved (default = ".").

    ARGS OUT:
    -------
    Path
        Path to the PNG's file.
    """

    summary_data = load_json(summary_confidences_path)

    full_data = process_full_data_af3(fulldata_path)
    
    pae_matrix = full_data["pae"] 
    chain_boundaries = full_data["chain_boundaries"] 
    chain_lengths = full_data["chain_lengths"]         
    
    fig, ax = plt.subplots(figsize=(8,6))
    im = ax.imshow(pae_matrix, cmap='Greens_r', origin='upper', vmin=0, vmax=25)

    for _, end_idx in chain_boundaries:
        ax.axhline(end_idx - 0.5, color='black', linewidth=1)
        ax.axvline(end_idx - 0.5, color='black', linewidth=1)

    midpoints = [(start_idx + end_idx) / 2 for start_idx, end_idx in chain_boundaries]
    chain_ids = list(chain_lengths.keys())
 
    ax.set_xticks(midpoints)
    ax.set_yticks(midpoints)
    ax.set_xticklabels(chain_ids)
    ax.set_yticklabels(chain_ids)
    
    axins = inset_axes(ax, width="100%", height="5%", loc="lower center", borderpad=-7)
    cbar = fig.colorbar(im, cax=axins, orientation="horizontal")  
    cbar_label = "Expected position error (Ångströms)"
    cbar.set_label(cbar_label)

    ax.set_title(f'pTM:{summary_data["ptm"]}| ipTM:{summary_data["iptm"]}', loc ="center")
    ax.set_xlabel("Residue Index")
    ax.set_ylabel("Residue Index")
    
    if save_name is None:
        plt.show()
    else:
        plt.savefig(save_name, dpi=300, bbox_inches="tight")
    plt.close(fig)

    return save_name

def batch_plotting(results_dir: str):
    """
    Process a directory and generates PAE figures.
    ARGS IN:
    ----------
    results_dir : str
        Directory containing the JSON files generated by AF3.

    ARGS OUT:
    -------
    list[Path]
        List of all generated PNG file paths.
    """
    results_dir = Path(results_dir)
   
    full_data_files= list(results_dir.glob("fold_*_full_data_*.json"))
    
    outputs = []
   
    for tmp_data_file in full_data_files:
        tmp_conf_file = str(tmp_data_file).replace("full_data", "summary_confidences")
        save_name_pae = str(tmp_data_file).replace(".json", "_pae").replace("full_data", "model")
        save_path_pae = Path (save_name_pae)
        save_name_plddt = str(tmp_data_file).replace(".json", "_plddt").replace("full_data", "model")
        save_path_plddt = Path (save_name_plddt)

        if save_path_pae.exists():
            outputs.append(save_path_pae)
        
        else:
            outfile_pae= plot_paes(tmp_conf_file, tmp_data_file, save_name=save_name_pae)
            outputs.append(outfile_pae)
        
        if save_path_plddt.exists():
            outputs.append(save_path_plddt)
        
        else:
            outfile_plddt = plot_pLDDT(tmp_data_file, save_name=save_name_plddt)
            outputs.append(outfile_plddt)

    return outputs


def plot_pLDDT (fulldata_path: str, save_name: str = None):
    
    full_data = process_full_data_af3 (fulldata_path)
    chain_boundaries_by_atom = full_data["chain_boundaries_by_atom"]
    atom_plddts = full_data["atom_plddts"]
    
    fig, ax = plt.subplots(figsize=(20, 5))

   
    max_length = len(atom_plddts)
    position = [n + 1 for n in range(len(atom_plddts))]

    ax.add_patch(Rectangle((0, 90), max_length, 10, color="#024fcc"))
    ax.add_patch(Rectangle((0, 70), max_length, 20, color="#60c2e8"))
    ax.add_patch(Rectangle((0, 50), max_length, 20, color="#f37842"))
    ax.add_patch(Rectangle((0, 0), max_length, 50, color="#f9d613"))

    ax.plot(
        position,
        atom_plddts,
        color="black",
        linewidth=0.5,
        linestyle="-"
            )
    ax.set_xlabel("Atom Position")
    
    ax.set_ylim(0, 100)
    ax.set_xlim(0, max(position) + 10)
    ax.spines[["right", "top"]].set_visible(False)
    ax.set_yticks([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])


    for _, end in chain_boundaries_by_atom:
        if end == max_length: break
        ax.axvline(x=end + 1, color="red", linestyle="dashed", linewidth=1)


    plddt_legend = {
        "Very high (pLDDT > 90)": "#024fcc",
        "High (90 > pLDDT > 70)": "#60c2e8",
        "Low (70 > pLDDT > 50)": "#f37842",
        "Very low (pLDDT < 50)": "#f9d613",
    }

    ax.legend(plddt_legend, title="pLDDT Confidence", prop={'size': 10}, 
            #   loc="lower center",
              bbox_to_anchor=(0.85, 1.15),
            frameon=False,
            ncol=4)

    ax.set_ylabel("pLDDT")

    if save_name is None:
        plt.tight_layout
        plt.show()
    else:
        plt.tight_layout
        plt.savefig(save_name, dpi=300, bbox_inches="tight")
    
    plt.close(fig)

    return save_name