
#------------------------------ IMPORTS -------------------------------------
import json
import subprocess
import os
import numpy as np
from pathlib import Path
import concurrent.futures
from concurrent.futures import ProcessPoolExecutor, as_completed
import pandas as pd
from glob import glob
import tqdm
from sklearn.cluster import DBSCAN
from .utils import process_full_data_af3
from .plotting import plot_boxplots, plot_iptm_vs_ptm, plot_pae_clusters

#------------------------------FUNCTIONS -----------------------------

def cluster_pae (pae_submatrix, threshold:int=15, eps:int=10)-> tuple:
    
    """
    Clusters low PAE regions in a PAE submatrix using DBSCAN.

    This function identifies coordinates in the PAE matrix where the predicted aligned error
    is below a given threshold, and applies DBSCAN clustering to group them. It returns the
    coordinates of low PAE values and their corresponding cluster labels.

    Parameters
    ----------
    pae_submatrix : np.ndarray
        A 2D array representing a subset of the PAE matrix.
    threshold : int, optional
        Maximum PAE value to consider for clustering (default is 15).
    eps : int, optional
        Maximum distance between points in a cluster for DBSCAN (default is 10).

    Returns
    -------
    tuple
        A tuple containing:
        - low_pae_coords (np.ndarray): Coordinates of low PAE values.
        - labels (np.ndarray or list): Cluster labels assigned by DBSCAN.

    Raises
    ------
    ValueError
        If the input matrix is invalid or clustering fails.
    """

    low_pae_coords = np.column_stack(np.where(pae_submatrix < threshold))
    if len(low_pae_coords)>0: ##Maybe we want something higher so we get rid of shit
        #Apply DBSCAN clustering
        clustering = DBSCAN(eps=eps, min_samples=5).fit(low_pae_coords)
        labels = clustering.labels_
    else:
        low_pae_coords, labels = [], []

    return  low_pae_coords, labels


def cluster_info (low_coords, cluster_labels)-> pd.DataFrame:
    
    """
    Extracts and summarizes geometric information from clustered low PAE coordinates.

    This function processes the output of a clustering algorithm (e.g., DBSCAN) applied to low PAE regions.
    For each cluster (excluding noise), it computes bounding box coordinates, percentiles to reduce outlier
    impact, and the cluster center. The results are returned as a pandas DataFrame.

    Parameters
    ----------
    low_coords : np.ndarray
        Array of coordinates (row, column) where PAE values are below a threshold.
    cluster_labels : np.ndarray
        Array of cluster labels assigned to each coordinate.

    Returns
    -------
    pd.DataFrame
        DataFrame containing geometric and statistical information for each cluster.

    Raises
    ------
    ValueError
        If input arrays are mismatched or improperly formatted.
    """

    cluster_info_list = []
    unique_labels = np.unique(cluster_labels)

    for label in unique_labels:
        if label == -1:
            continue  # Ignorar ruido

        cluster_coords = low_coords[cluster_labels == label]

        # Clustering functions (x 1 y 0)
        x_min = np.min(cluster_coords[:, 1])
        y_max = np.max(cluster_coords[:, 0])
        x_max = np.max(cluster_coords[:, 1])
        y_min = np.min(cluster_coords[:, 0])

        cluster_center = np.mean(cluster_coords, axis=0)

        #Percentiles to reduce the impact of outliers
        top_percentile = np.percentile(cluster_coords, 99.5, axis=0)
        lower_percentile = np.percentile(cluster_coords, .5, axis=0)
        per_x_min = lower_percentile[1]
        per_y_min = lower_percentile[0]
        per_x_max = top_percentile[1]
        per_y_max = top_percentile[0]

        cluster_info_list.append({
            "cluster_id": label,
            "x_min": x_min,
            "x_max": x_max,
            "y_min": y_min,
            "y_max": y_max,
            "percentile_x_min": per_x_min,
            "percentile_x_max": per_x_max,
            "percentile_y_min": per_y_min,
            "percentile_y_max": per_y_max,
            "center_x": cluster_center[1],
        })

    # Generate the pd.df
    cluster_data_from_model = pd.DataFrame(cluster_info_list)
    
    return cluster_data_from_model
    
def process_cif_file (cif_file: str)-> tuple[list, pd.DataFrame]:

    """
    Processes an AlphaFold3 CIF model file and extracts structural and confidence metrics.

    This function parses metadata from the CIF file path, loads associated JSON files containing
    summary confidences and full structural data, and computes various metrics such as pLDDT means,
    PAE means (overall and per chain), and clustering information from the PAE submatrix between chains.
    It also generates a cluster plot and returns both summary metrics and cluster details.

    Parameters
    ----------
    cif_file : str
        Path to the CIF file generated by AlphaFold3.

    Returns
    -------
    list
        A list containing summary metrics:
        [ppi_id, orf_a, orf_b, folder_path, model_number, fraction_disordered, iPTM, pTM,
        chain_length_A, chain_length_B, plddt_mean, plddt_mean_chain_A, plddt_mean_chain_B,
        mean_pae, mean_pae_chain_A, mean_pae_chain_B, mean_pae_chain_A_B]
    pd.DataFrame
        DataFrame containing cluster information extracted from the PAE submatrix.

    Raises
    ------
    FileNotFoundError
        If associated JSON files are missing.
    KeyError
        If expected keys are missing in the JSON data.
    ValueError
        If the CIF file path format is invalid or model number cannot be extracted.
    """
    
    # Extract folder name and model number
    folder_path = "/".join(cif_file.split("/")[1:-1])
    ppi_id = cif_file.split("/")[-2].replace("adv5_", "")
    orf_a, orf_b = ppi_id.split("__")
    model_number = int(cif_file.split("/")[-1].split("_")[-1].replace(".cif", ""))
    # Name for summary confidences file
    summary_confidences_file = cif_file.replace(".cif",".json").replace("model","summary_confidences")
    # Name for full data file 
    full_data_file = summary_confidences_file.replace("summary_confidences","full_data")
    # Open summary confidences file
    with open (summary_confidences_file,"r") as sc:
        # Load json data
        summary_data = json.load(sc)
        # Extract fraction disordered, iPTM and pTM
        fraction_disordered = summary_data["fraction_disordered"]
        iPTM = summary_data["iptm"]
        pTM = summary_data["ptm"]
    # Process full data file (json file)
    full_data = process_full_data_af3(full_data_file)
  
    # Extract the length of chain A and chains B
    chain_lenghts = full_data["chain_lengths"]
    chain_lenght_A = chain_lenghts["A"]
    chain_lenght_B = chain_lenghts["B"]

    ## Add plddt mean 
    plddt_mean = np.mean(full_data["atom_plddts"])

    ## Add plddt_mean_chain_A
    ## Extract the start and end of atoms boundaries for chain A
    start_a_atoms, end_a_atoms = full_data["chain_boundaries_by_atom"][0]
    end_a_atoms += 1
    ## Indexing in atom_plddts using the boundaries in order to calculate the mean
    plddt_mean_chain_A = np.mean(full_data["atom_plddts"][start_a_atoms:end_a_atoms])
    
    ## Add plddt_mean_chain_B
    ## Extract the start and end of atoms boundaries for chain B
    start_b_atoms, end_b_atoms = full_data["chain_boundaries_by_atom"][1]
    end_b_atoms += 1
    ## Indexing in atom_plddts using the boundaries in oder to calculate the mean
    plddt_mean_chain_B = np.mean(full_data["atom_plddts"][start_b_atoms:end_b_atoms])
    
    ## Add mean PAE
    mean_pae = np.mean(full_data["pae"])
    
    ## Add mean PAE chain A
    ## Extract the start and end of residues boundaries for chain A
    start_a_residues, end_a_residues = full_data["chain_boundaries"][0]
    end_a_residues += 1
    ## Generate the pae matrix for chain A 
    pae_chain_A = full_data["pae"][start_a_residues:end_a_residues,start_a_residues:end_a_residues]
    mean_pae_chain_A = np.mean(pae_chain_A)

    ## Add mean PAE chain B
    ## Extract the start and end of residues boundaries for chain B
    start_b_residues, end_b_residues = full_data["chain_boundaries"][1]
    end_b_residues += 1
    ## Generate the pae matrix for chain B
    pae_chain_B = full_data["pae"][start_b_residues:end_b_residues,start_b_residues:end_b_residues]
    mean_pae_chain_B = np.mean(pae_chain_B)

    ## Add mean PAE pair A-B
    ## Generate the pae matrix for chain A-B
    pae_chain_A_B = full_data["pae"][start_a_residues:end_a_residues,start_b_residues:end_b_residues]
    mean_pae_chain_A_B = np.mean(pae_chain_A_B)   
    
    ## Here, we do cluster of PAE AB submatrix, we already have the submatrix
    submatrix = pae_chain_A_B

    ## here we do the clutering
    low_coords, cluster_labels = cluster_pae(submatrix)

    ## here we do the plot of the pae clusters
    plot_pae_clusters(submatrix,low_coords, cluster_labels, save_name=cif_file.replace(".cif", "_cluster.png")) 
    
    cluster_data = cluster_info(low_coords=low_coords, cluster_labels=cluster_labels)
    # Incluir en el df de los clusters el ppi_id
    # import pdb;pdb.set_trace()
    if len(cluster_data)>0:
        cluster_data.loc[:, "PPI"] = ppi_id 
        cluster_data.loc[:, "Model_num"] = model_number 

    
    return [ppi_id, orf_a, orf_b, folder_path, model_number, fraction_disordered, iPTM, 
                        pTM, chain_lenght_A, chain_lenght_B, 
                        # contact_probs,
                         plddt_mean, plddt_mean_chain_A, plddt_mean_chain_B,
                          mean_pae, mean_pae_chain_A, mean_pae_chain_B,
                        #   min_pae_chain_A, min_pae_chain_B, 
                          mean_pae_chain_A_B], cluster_data

## Creating simplified dataframe with info of individual proteins
def get_info_for_proteins(df)-> pd.DataFrame:
    """
    Extracts per-protein metrics from a DataFrame containing chain-level information.

    This function takes a DataFrame with metrics for chain A and chain B of protein-protein interactions,
    renames the columns to unify the format, and concatenates the data to produce a per-ORF summary.
    Useful for downstream analysis of individual protein metrics across models.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing columns for ORF_A, ORF_B, PPI, Model_num, and chain-specific metrics.

    Returns
    -------
    pd.DataFrame
        A DataFrame with unified columns:
        ["ORF", "PPI", "Model_num", "plddt_mean_ORF", "pae_mean_ORF"]

    Raises
    ------
    KeyError
        If expected columns are missing in the input DataFrame.
    """

    info_from_chain_a = df.loc[:, ["ORF_A", "PPI", "Model_num", 
                                   "plddt_mean_chain_A", "mean_pae_chain_A"]]

    info_from_chain_b = df.loc[:, ["ORF_B", "PPI", "Model_num", 
                                   "plddt_mean_chain_B", "mean_pae_chain_B"]]

    info_from_chain_a.columns = ["ORF", "PPI", "Model_num", 
                                 "plddt_mean_ORF", "pae_mean_ORF"]

    info_from_chain_b.columns = ["ORF", "PPI", "Model_num", 
                                 "plddt_mean_ORF", "pae_mean_ORF"]
    by_protein_df = pd.concat([info_from_chain_a, info_from_chain_b], 
                              ignore_index=True) 
    return by_protein_df   
   

def process_interactome(folder_path:str, output_path:str, **kwargs):    
    
    """
    Processes an AlphaFold3 interactome folder and generates summary data, cluster analysis, and visualizations.

    This function scans a directory for CIF model files, extracts structural and confidence metrics from each,
    aggregates the results into summary DataFrames, and saves them as CSV files. It also generates boxplots
    and scatterplots for pLDDT, PAE, and ipTM vs pTM metrics.

    Parameters
    ----------
    folder_path : str
        Path to the root directory containing AlphaFold3 model subfolders with CIF files.
    output_path : str
        Directory where output CSVs and plots will be saved.
    **kwargs : dict
        Optional keyword arguments passed to the ProcessPoolExecutor (e.g., max_workers).

    Returns
    -------
    None

    Raises
    ------
    ValueError
        If no CIF files are found in the specified folder.
    FileNotFoundError
        If required JSON files associated with CIF models are missing.
    """

    ## TODO:Check and create the output path

    # Extract the .cif files (list with all cif files)
    all_cif_files = glob(f"{folder_path}/*/*cif") ## For testing  
    # all_cif_files = glob(f"{folder_path}/*/*cif")

 
    if len(all_cif_files)==0:
        raise ValueError(f"""No files found in the directory {folder_path}.
                         Please make sure it follows the AF3 output directory convention""")
    
    print(all_cif_files)

    # Paralelización

    #List of tuples -> every tuple has list,df
    ##TODO: skip this is .csv exists
    interactome_df_list = []
    cluster_df_list = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
    # with concurrent.futures.ProcessPoolExecutor(**kwargs) as executor:
         # map devuelve los resultados en orden de la lista
        for res in tqdm.tqdm(executor.map(process_cif_file, all_cif_files)): #For testing
            interactome_df_list.append(res[0])
            cluster_df_list.append(res[1])
    # Create the df with the info of all PPIs
    # interactome_df_list = [list[0] for list in results] 
    interactome_df = pd.DataFrame(interactome_df_list,
                     columns=["PPI", "ORF_A", "ORF_B", "Folder", "Model_num","Fraction_disordered","iPTM","pTM",
                             "chain_lenght_A","chain_lenght_B", 
                             #    "contact_probs",
                             "plddt_mean", "plddt_mean_chain_A","plddt_mean_chain_B",
                             "mean_pae", "mean_pae_chain_A", "mean_pae_chain_B",
                             #    "min_pae_chain_A", "min_pae_chain_B",
                             "mean_pae_chain_A_B"])
    interactome_df.reset_index(inplace=True, drop=True)

    # Join the dfs of the clusters in a single df
    # non_empty_cluster_info = filter(lambda x: len(x)>0, cluster_df_list)
    clusters_df = pd.concat(cluster_df_list, ignore_index=True)
    # clusters_df = pd.concat(non_empty_cluster_info, ignore_index=True)
    # clusters_df = pd.concat([df[1] for df in results], ignore_index=True)

    # Save dfs to .csv
    interactome_df.to_csv(f'{output_path}/interactome_data.csv', index=False)
    clusters_df.to_csv(f'{output_path}/clusters_data.csv', index=False)
    by_protein_df = get_info_for_proteins(interactome_df)
    by_protein_df.to_csv(f'{output_path}/interactome_data_by_protein.csv', index=False) 

    ## Plotting boxplots
    output_folder = f"{output_path}/plots"
    plddt_array, labels_array1 = process_boxplot_data(by_protein_df, "plddt_mean_ORF")
    pae_array, labels_array2 = process_boxplot_data(by_protein_df, "pae_mean_ORF")
    plot_boxplots("plddt",plddt_array, labels_array1, output_path=output_folder)
    plot_boxplots("pae",pae_array,labels_array2, output_path=output_folder)

    ## Plotting scatterplots
    plot_iptm_vs_ptm(interactome_df, output_path=output_folder)


def process_boxplot_data(df, value_column:str)->tuple[np.ndarray, np.ndarray]:

    """
    Prepares data for boxplot visualization by grouping values per ORF.

    This function takes a DataFrame and a column name (e.g., pLDDT or PAE values),
    groups the values by ORF, computes the mean for sorting, and returns the data
    in a format suitable for plotting: a matrix of values and a corresponding list of labels.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing at least the columns "ORF" and the specified value column.
    value_column : str
        Name of the column containing the values to be grouped and plotted.

    Returns
    -------
    tuple
        A tuple containing:
        - value_matrix : np.ndarray
            Array of lists, each containing values for an ORF, sorted by mean value.
        - labels_list : np.ndarray
            Array of ORF names corresponding to the sorted value_matrix.

    Raises
    ------
    KeyError
        If the specified value_column or "ORF" is missing from the DataFrame.
    """

    grouped_values = []
    orf_labels = []
    for orf in df["ORF"].unique():
        tmp = list(df.loc[df["ORF"] == orf , value_column])
        grouped_values.append(tmp) 
        orf_labels.append(orf)
            
    mean_values = [np.mean(v) for v in grouped_values]
    sort_idx = np.argsort(mean_values)    
    value_matrix = np.array(grouped_values, dtype=object)[sort_idx]    
    orf_labels = np.array(orf_labels)[sort_idx]
    
    return value_matrix, orf_labels


def run_single_ipsae(cmd, folder):
    '''
    
    Executes a single ipSAE command within the specified folder.

    Parameters:
    cmd (str): The command to execute, typically a call to the 'ipsae.py' script with arguments.
    folder (str or Path): The directory in which the command should be executed.

    Returns:
    None

    '''
    subprocess.run(cmd, shell=True, cwd=folder)

def run_ipsae_for_all_parallel(base_dir: str, ipsae_script: str, 
                               pae_cutoff: int =15, dist_cutoff: int =10, 
                               dry_run: bool=False, n_cores: int=4)->list:
    '''

    Runs ipSAE scoring in parallel on all AlphaFold3 models (JSON + CIF files) found in subdirectories of 'base_dir'.
    Displays a tqdm progress bar during execution.

    Parameters:
    base_dir (str or Path): the root directory containing subfolders with AlphaFold3 model files.
    ipsae_script (str or Path): path to the ipSAE script to be executed.
    pae_cutoff (int): PAE cutoff value used in scoring. Default is 15.
    dist_cutoff (int): distance cutoff value used in scoring. Default is 10.
    dry_run (bool): if True, prints the commands without executing them. Default is False.
    n_cores (int): number of parallel processes to use. Default is 4.

    Returns:
    List[str]: a list of executed (or printed, if dry_run=True) commands.

    '''
    
    base_dir = Path(base_dir)
    ipsae_script = Path(ipsae_script)
    commands_run = []

    # Collect all commands
    for folder in base_dir.rglob("*"):
        if not folder.is_dir():
            continue
        json_files = list(folder.glob("*.json"))
        cif_files = list(folder.glob("*.cif"))
        for json_file in json_files:
            for cif_file in cif_files:
                cmd = f"python {ipsae_script} {json_file} {cif_file} {pae_cutoff} {dist_cutoff}"
                commands_run.append((cmd, folder))

    print(f"Found {len(commands_run)} commands for AF3 models.")

    if dry_run:
        for cmd, folder in commands_run:
            print(f"[DRY RUN] {cmd}  (folder: {folder})")
        return [c[0] for c in commands_run]

    # Run in parallel with progress bar
    results = []
    with ProcessPoolExecutor(max_workers=n_cores) as executor:
        futures = {executor.submit(run_single_ipsae, cmd, folder): (cmd, folder) for cmd, folder in commands_run}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Running ipSAE", unit="model"):
            try:
                future.result()  # will raise exceptions if any
            except Exception as e:
                cmd, folder = futures[future]
                print(f"Error running {cmd} in {folder}: {e}")
            results.append(futures[future][0])

    return results


def merge_ipsae_results(base_dir: str, pae_cutoff: int =15, 
                        dist_cutoff: int =10,
                        save_local: bool =True, 
                        save_summary: bool =True)-> tuple:
    """
    Process ipSAE results across multiple subfolders.

    This function:
      - Scans all subdirectories inside the base directory
      - Reads ipSAE result files (*_<pae>_<dist>.txt and *_byres.txt)
      - Saves one combined CSV per subfolder (if save_local=True)
      - Optionally generates a global summary CSV combining all data (if save_summary=True)

    Parameters
    ----------
    base_dir : str or Path
        Path to the main directory containing the ipSAE result folders.
    pae_cutoff : int, optional
        PAE cutoff value used in file names (default is 15).
    dist_cutoff : int, optional
        Distance cutoff value used in file names (default is 10).
    save_local : bool, optional
        If True, save individual CSVs inside each subfolder.
    save_summary : bool, optional
        If True, save global summary CSVs in the base directory.

    Returns
    -------
    df_global_all : pandas.DataFrame
        Combined DataFrame with all global interaction scores.
    df_byres_all : pandas.DataFrame
        Combined DataFrame with all residue-level scores.
    """

    base_dir = Path(base_dir)
    dfs_global, dfs_byres = [], []

    pattern_global = f"*_{pae_cutoff}_{dist_cutoff}.txt"
    pattern_byres = f"*_{pae_cutoff}_{dist_cutoff}_byres.txt"

    # Loop through all subfolders 
    for folder in base_dir.iterdir():
        if not folder.is_dir():
            continue
        
        folder_global, folder_byres = [], []
        for file in folder.glob(pattern_global):
            if "byres" in file.name:
                continue
            model = file.stem.split("_model_")[-1].split("_")[0]
            try:
                df = pd.read_csv(file, sep=r"\s+", engine="python")
                df["Folder"] = folder.name
                df["Model"] = model
                folder_global.append(df)
                dfs_global.append(df)
            except Exception as e:
                print(f"Error reading {file}: {e}")

        for file in folder.glob(pattern_byres):
            model = file.stem.split("_model_")[-1].split("_")[0]
            try:
                df = pd.read_csv(file, sep=r"\s+", engine="python")
                df["Folder"] = folder.name
                df["Model"] = model
                folder_byres.append(df)
                dfs_byres.append(df)
            except Exception as e:
                print(f"Error reading {file}: {e}")

        # Save local CSVs inside each subfolder
        if save_local:
            if folder_global:
                pd.concat(folder_global).to_csv(folder / f"{folder.name}_ipSAE_global.csv", index=False)
            if folder_byres:
                pd.concat(folder_byres).to_csv(folder / f"{folder.name}_ipSAE_byres.csv", index=False)

    # Combine everything
    df_global_all = pd.concat(dfs_global, ignore_index=True) if dfs_global else pd.DataFrame()
    df_byres_all = pd.concat(dfs_byres, ignore_index=True) if dfs_byres else pd.DataFrame()

    # Save global summary in the base directory
    if save_summary:
        if not df_global_all.empty:
            df_global_all.to_csv(base_dir / "ipSAE_global_all.csv", index=False)
        if not df_byres_all.empty:
            df_byres_all.to_csv(base_dir / "ipSAE_byres_all.csv", index=False)

    print(f"Processed {len(list(base_dir.iterdir()))} subfolders")
    print(f"{len(df_global_all)} global rows, {len(df_byres_all)} by-residue rows")

    return df_global_all, df_byres_all






        


   




