import json
import yaml
from collections import OrderedDict
import numpy as np
from typing import Union, Dict, List, Any
from glob import glob
import numpy as np
import os
from moleculekit.molecule import Molecule
from pathlib import Path
from .metrics import ptm_func_vec, calc_d0


def check_sequence_validity(seq: str) -> bool:
    VALID_AMINO_ACIDS = set("ACDEFGHIKLMNPQRSTVWY")
    return all(residue in VALID_AMINO_ACIDS for residue in seq)

def parse_msa_metrics(a3m_path: str) -> Dict[str, float]:
    """
    Parses a ColabFold .a3m file to extract MSA depth and mean coverage.
    
    Parameters
    ----------
    a3m_path : str
        Path to the .a3m file.
        
    Returns
    -------
    dict
        Dictionary with 'msa_depth' (int) and 'msa_coverage' (float 0-1).
    """
    if not os.path.exists(a3m_path):
        return {"msa_depth": 0, "msa_coverage": 0.0}
    
    sequences = []
    with open(a3m_path, "r") as f:
        for line in f:
            if not line.startswith(">"):
                sequences.append(line.strip())
    
    if not sequences:
        return {"msa_depth": 0, "msa_coverage": 0.0}
    
    query = sequences[0]
    query_len = len(query.replace("-", ""))
    
    # Depth: number of sequences (excluding query)
    depth = len(sequences) - 1
    
    # Coverage: average fraction of non-gap residues in the alignment relative to query
    # Simple estimate: mean of (non-gap residues / query_len) for all hits
    coverage_sum = 0.0
    for seq in sequences[1:]:
        non_gaps = len(seq.replace("-", "").replace(".", ""))
        coverage_sum += min(1.0, non_gaps / query_len)
    
    mean_coverage = coverage_sum / depth if depth > 0 else 0.0
    
    return {
        "msa_depth": depth,
        "msa_coverage": round(mean_coverage, 3)
    }

def load_json(json_path: str)-> Union[dict, list]:
    """
    Loads and parses a JSON file from the specified path.

    This function opens a JSON file and returns its contents as a Python dictionary
    or list, depending on the structure of the JSON.

    Parameters
    ----------
    json_path : str
        Path to the JSON file to be loaded.

    Returns
    -------
    dict or list
        Parsed content of the JSON file.

    Raises
    ------
    FileNotFoundError
        If the specified file does not exist.
    json.JSONDecodeError
        If the file is not a valid JSON.
    """

    with open (json_path,"r") as j:
        data = json.load(j)
    return data

def load_yaml(yaml_path: Union[str, Path]) -> Any:
    """
    Loads a YAML file safely with UTF-8 encoding.

    Args:
        yaml_path (Union[str, Path]): Path to the YAML file.

    Returns:
        Any: The parsed contents of the YAML file (usually a dict or list).
    """
    path_obj = Path(yaml_path)

    with open(path_obj, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def load_boltz_input(yaml_path: Union[str, Path], job_name: str | None  = None)-> List[Dict[str, Any]]:
    """
    Loads a Boltz YAML file and standardizes it to the internal list-based format.
    
    This function acts as a 'Hybrid Adapter': it supports both the modern list-based 
    IDs generated by InteractomeWriter (e.g., id: ['A', 'B']) and legacy formats 
    using the 'multiple_chains' field.

    Args:
        yaml_path (Union[str, Path]): Path to the YAML file.
        job_name (str | None, optional): Custom name for the job. If None, 
            derived from the filename.

    Returns:
        List[Dict[str, Any]]: A list containing the job dictionary, structured 
        compatibly with the AF3 processing pipeline.
    """
    data = load_yaml(yaml_path)

    if job_name is None:
        job_name = Path(yaml_path).stem

    sequence_info = []
    
    # Safely get sequences list
    raw_sequences = data.get("sequences", [])

    for seq_entry in raw_sequences:
        protein_data = seq_entry.get("protein", {})
        prot_id = protein_data.get("id")
        seq_str = protein_data.get("sequence", "")
       
        #--- HYBRID LOGIC ---
        if isinstance(prot_id, list):
            # NEW FORMAT: id: ['A', 'B']
            count = len(prot_id)

        elif isinstance(prot_id, str):
            # LEGACY FORMAT: multiple_chains: "B,C"
            multi = protein_data.get("multiple_chains")
            if multi:
                count = multi.count(",") + 2 
            else:
                count = 1
        else:
            count = 1


        tmp_sequence_info = {
            "proteinChain":{
                "sequence": seq_str,
                "count": count,
            }
        }
        sequence_info.append(tmp_sequence_info)
    job = [
        {
            "name": job_name,
            "sequences": sequence_info
        }
    ]
    return job


def process_full_data_boltz(mol_file: str, 
                            pae_file: str | None = None,
                            plddt_file: str | None = None,
                            pde_file: str | None = None,
                            confidence_file: str | None = None,
                            )-> dict:
    """
    Process Boltz output files and return structural confidence data.

    Parameters
    ----------
    mol_file : str
        Path to the main CIF file (mandatory).
    confidence_file : str, optional
        Path to the confidence JSON file. If None, it will be inferred.
    pae_file : str, optional
        Path to the PAE NPZ file. If None, it will be inferred.
    plddt_file : str, optional
        Path to the pLDDT NPZ file. If None, it will be inferred.
    pde_file : str, optional
        Path to the PDE NPZ file. If None, it will be inferred.
    confidence_file : str, optional
        Path to the summary confidences JSON file. If None, it will be inferred.
    Returns
    -------
    dict
        Dictionary containing:
        - 'pae': numpy.ndarray, PAE matrix
        - 'plddt': numpy.ndarray, pLDDT scores
        - 'ptm': float, predicted TM-score (if available)
        - 'iptm': float, interface predicted TM-score (if available)

    Raises
    ------
    FileNotFoundError
        If any required file cannot be found.
    ValueError
        If the NPZ files do not contain expected arrays.
    """

    base_name = os.path.splitext(os.path.basename(mol_file))[0]  # pvi__protease_model_0
    dir_name = os.path.dirname(mol_file)

    # Deduce rutas si no se pasan
    if confidence_file is None:
        confidence_file = os.path.join(dir_name, f"confidence_{base_name}.json")
    if pae_file is None:
        pae_file = os.path.join(dir_name, f"pae_{base_name}.npz")
    if plddt_file is None:
        plddt_file = os.path.join(dir_name, f"plddt_{base_name}.npz")
    if pde_file is None:
        pde_file = os.path.join(dir_name, f"pde_{base_name}.npz")

    # Validate file existence
    for file_path, description in [
        (mol_file, "molecule CIF/PDB"),
        (confidence_file, "confidence JSON"),
        (pae_file, "PAE NPZ"),
        (plddt_file, "pLDDT NPZ"),
        (pde_file, "PDE NPZ"),
    ]:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Missing {description} file: {file_path}")

    mol = Molecule(mol_file)
    pae_data = np.load(pae_file)["pae"]
    pde_data = np.load(pde_file)["pde"]
    plddt_data = np.load(plddt_file)["plddt"] * 100 ## In AF3 we have range 1-100
    confidence_data = load_json(confidence_file)
    chain_by_res = mol.chain[mol.name == "CA"]


    if pae_data.shape != pde_data.shape:
        raise ValueError(f"PAE and PDE shapes do not match: {pae_data.shape} vs {pde_data.shape}")

    if pae_data.shape[0] != len(plddt_data):
        raise ValueError(f"pLDDT length ({len(plddt_data)}) does not match PAE size ({pae_data.shape[0]})")

    if len(chain_by_res) != len(plddt_data):
        raise ValueError(f"pLDDT length ({len(plddt_data)}) does not match chain_by_res size ({len(chain_by_res)})")

    ## Check dimensions 
    chain_boundaries = {}
    chain_boundaries_by_atom = {}
  
    for chain_id in np.unique(mol.chain):
        chain_indexes = np.where(np.array(chain_by_res) == chain_id)
        chain_boundaries[chain_id] = (np.min(chain_indexes), np.max(chain_indexes))
        atom_chain_indexes = np.where(np.array(mol.chain) == chain_id)
        chain_boundaries[chain_id] = (np.min(chain_indexes), np.max(chain_indexes))
        chain_boundaries_by_atom[chain_id] = (np.min(atom_chain_indexes), np.max(atom_chain_indexes))
    
    iptm_by_chain = confidence_data.get("pair_chains_iptm", None)
    ndim = len(iptm_by_chain)
    iptm_by_chain_as_list = np.zeros((ndim, ndim))
    for i in range(len(iptm_by_chain)):
        for j in range(len(iptm_by_chain)):
            iptm_by_chain_as_list[i,j] = iptm_by_chain[str(i)].get(str(j), None)

    return {"pae": pae_data, 
            "atom_plddts": mol.beta,
            "cb_plddts": plddt_data,
            "ca_plddts": plddt_data,
            "chain_boundaries_by_res": chain_boundaries,
            "chain_boundaries_by_atom": chain_boundaries_by_atom,
            "token_chain_ids": chain_by_res,
            "ptm": confidence_data.get("ptm", None),
            "iptm": confidence_data.get("iptm", None),
            "iptm_chain_pair": iptm_by_chain_as_list}

def process_full_data_colabfold(mol_file: str,
                               scores_json_path: str | None = None) -> dict:
    """
    Process ColabFold output files and return standardized structural confidence data.

    Infers the scores JSON from the model PDB filename by replacing
    '_unrelaxed_' or '_relaxed_' with '_scores_'.

    Parameters
    ----------
    mol_file : str
        Path to the ranked PDB/CIF model file (mandatory).
    scores_json_path : str, optional
        Path to the scores JSON file. If None, inferred from mol_file.

    Returns
    -------
    dict
        Standardized dictionary with keys:
        'pae', 'atom_plddts', 'ca_plddts', 'cb_plddts',
        'chain_boundaries_by_res', 'chain_boundaries_by_atom',
        'token_chain_ids', 'ptm', 'iptm', 'iptm_chain_pair'.

    Raises
    ------
    FileNotFoundError
        If the model file or scores JSON cannot be found.
    ValueError
        If PAE/pLDDT dimensions do not match the structure.
    """
    base_path = Path(mol_file)
    dir_name = base_path.parent
    stem = base_path.stem  # e.g. NAME_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000

    if scores_json_path is None:
        scores_stem = stem.replace("_unrelaxed_", "_scores_").replace("_relaxed_", "_scores_")
        scores_json_path = str(dir_name / f"{scores_stem}.json")

    # Path for .a3m file (MSA)
    # Standard: name.a3m (one level up or same folder depending on run strategy)
    a3m_path = str(dir_name / f"{stem.split('_unrelaxed_')[0]}.a3m")
    if not os.path.exists(a3m_path):
        # Fallback: check one level up if using individual fastas
        a3m_path = str(dir_name.parent / f"{stem.split('_unrelaxed_')[0]}.a3m")

    for file_path, description in [
        (mol_file, "molecule PDB/CIF"),
        (scores_json_path, "scores JSON"),
    ]:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Missing {description} file: {file_path}")

    mol = Molecule(mol_file)
    scores_data = load_json(scores_json_path)
    msa_metrics = parse_msa_metrics(a3m_path) if os.path.exists(a3m_path) else {"msa_depth": 0, "msa_coverage": 0.0}

    # CA-level arrays
    chain_by_res = mol.chain[mol.name == "CA"]
    pae_data = np.array(scores_data["pae"])          # already in Angstroms
    plddt_data = np.array(scores_data["plddt"])       # already 0-100

    n_res = len(chain_by_res)
    if pae_data.shape[0] != n_res:
        raise ValueError(
            f"PAE size ({pae_data.shape[0]}) != CA atom count ({n_res})"
        )
    if len(plddt_data) != n_res:
        raise ValueError(
            f"pLDDT length ({len(plddt_data)}) != CA atom count ({n_res})"
        )

    # Chain boundaries
    chain_boundaries: Dict[str, Any] = {}
    chain_boundaries_by_atom: Dict[str, Any] = {}
    unique_chains = np.unique(chain_by_res)

    for chain_id in unique_chains:
        res_idxs = np.where(chain_by_res == chain_id)[0]
        chain_boundaries[chain_id] = (int(res_idxs.min()), int(res_idxs.max()))
        atom_idxs = np.where(mol.chain == chain_id)[0]
        chain_boundaries_by_atom[chain_id] = (int(atom_idxs.min()), int(atom_idxs.max()))

    # ColabFold does not provide per-chain iptm; estimate manually from PAE
    n_chains = len(unique_chains)
    iptm_chain_pair = np.zeros((n_chains, n_chains))

    for i, chain_i in enumerate(unique_chains):
        for j, chain_j in enumerate(unique_chains):
            mask_i = (chain_by_res == chain_i)
            mask_j = (chain_by_res == chain_j)
            
            # Select PAE submatrix for these two chains
            pae_block = pae_data[mask_i][:, mask_j]
            
            # Calculate d0 based on chain lengths
            # For pTM (diagonal i==j), use single chain length.
            # For ipTM (off-diagonal i!=j), use sum of lengths.
            L_eff = np.sum(mask_i) + np.sum(mask_j) if i != j else np.sum(mask_i)
            d0 = calc_d0(L_eff, 'protein')
            
            # Calculate mean pTM/ipTM score for this pair/chain
            iptm_chain_pair[i, j] = np.mean(ptm_func_vec(pae_block, d0))

    return {
        "pae": pae_data,
        "atom_plddts": mol.beta,
        "ca_plddts": plddt_data,
        "cb_plddts": plddt_data,          # CA used as proxy (no separate CB file)
        "chain_boundaries_by_res": chain_boundaries,
        "chain_boundaries_by_atom": chain_boundaries_by_atom,
        "token_chain_ids": chain_by_res,
        "ptm": scores_data.get("ptm", None),
        "iptm": scores_data.get("iptm", None),
        "iptm_chain_pair": iptm_chain_pair,
        **msa_metrics,
    }


def process_full_data_af3(mol_file: str,
                          json_path: str | None = None,
                          summary_json_path: str | None = None,)-> dict: ## Maybe this should be a mol_file also?
    
    """
    Processes AlphaFold3 full data JSON and extracts structural metadata.

    This function loads a JSON file containing AlphaFold3 output, computes chain lengths,
    boundaries (both residue and atom-level), and converts key fields to NumPy arrays for
    efficient downstream analysis. It enriches the original data with additional structural
    annotations.

    Parameters
    ----------
    json_path : str
        Path to the JSON file containing AlphaFold3 full data output.

    Returns
    -------
    dict
        Dictionary containing the original data plus:
        - "chain_lengths": OrderedDict with residue counts per chain.
        - "chain_boundaries": List of tuples with residue index ranges per chain.
        - "chain_boundaries_by_atom": List of tuples with atom index ranges per chain.
        - "pae", "atom_plddts", "contact_probs": Converted to NumPy arrays.

    Raises
    ------
    FileNotFoundError
        If the JSON file does not exist.
    KeyError
        If expected keys are missing in the JSON structure.
    """
    from moleculekit.molecule import Molecule

    if json_path is None:
        json_path = mol_file.replace("_model_", "_full_data_").replace(".cif", ".json")
    if summary_json_path is None:
        summary_json_path = mol_file.replace("_model_", "_summary_confidences_").replace(".cif", ".json")

    # Validate file existence
    for file_path, description in [
        (mol_file, "molecule CIF/PDB"),
        (json_path, "full data JSON"),
        (summary_json_path, "confidence JSON"),
    ]:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Missing {description} file: {file_path}")
    full_data = load_json(json_path)
    summary_data = load_json(summary_json_path)
    token_chain_ids = np.array(full_data.get("token_chain_ids"))
    atom_chain_ids = np.array(full_data.get("atom_chain_ids"))
    
    mol = Molecule(mol_file)
    chain_by_res = mol.chain[mol.name == "CA"]

    # mol_path = json_path.replace("full_data", "model").replace(".json", ".cif")
    mol = Molecule(mol_file)
    ca_mask = mol.name == "CA"
    cb_mask = np.logical_or(mol.name == "CB", np.logical_and(mol.resname == "GLY",  mol.name == "CA"))
    cb_plddt = np.array(full_data.get("atom_plddts"))[cb_mask]
    ca_plddt = np.array(full_data.get("atom_plddts"))[ca_mask]
    
    chain_boundaries = {}
    chain_boundaries_by_atom = {}
    for chain_id in np.unique(token_chain_ids):
        chain_indexes = np.where(np.array(chain_by_res) == chain_id)
        chain_boundaries[str(chain_id)] = (int(np.min(chain_indexes)), int(np.max(chain_indexes)))
        
        atom_chain_indexes = np.where(atom_chain_ids == chain_id)
        chain_boundaries_by_atom[str(chain_id)] = (np.min(atom_chain_indexes), np.max(atom_chain_indexes))

    ## Convert pae, atom_plddts and contact_probs to np arrays
    full_data["pae"] = np.array(full_data["pae"])
    full_data["ptm"] = summary_data["ptm"]
    full_data["iptm"] = summary_data["iptm"]
    full_data["iptm_chain_pair"] = np.array(summary_data["chain_pair_iptm"])
    full_data["atom_plddts"] = np.array(full_data["atom_plddts"])
    full_data["cb_plddts"] = np.array(cb_plddt)
    full_data["ca_plddts"] = np.array(ca_plddt)
    # full_data["contact_probs"] = np.array(full_data["contact_probs"])
    full_data["token_chain_ids"] = token_chain_ids
    
    # full_data["chain_lengths"] = chain_lengths 
    full_data["chain_boundaries_by_res"] = chain_boundaries
    full_data["chain_boundaries_by_atom"] = chain_boundaries_by_atom
    return full_data
